// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package ygen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/openconfig/goyang/pkg/yang"
)

// protoMsgField describes a field of a protobuf message.
type protoMsgField struct {
	Tag        uint32            // Tag is the field number that should be used in the protobuf message.
	Name       string            // Name is the field's name.
	Type       string            // Type is the protobuf type for the field.
	IsRepeated bool              // IsRepeated indicates whether the field is repeated.
	Extensions map[string]string // Extensions is the set of field tags that are applied to the field.
}

// protoMsg describes a protobuf message.
type protoMsg struct {
	Name     string           // Name is the name of the protobuf message to be output.
	YANGPath string           // YANGPath stores the path that the message corresponds to within the YANG schema.
	Fields   []*protoMsgField // Fields is a slice of the fields that are within the message.
}

var (
	// protoHeaderTemplate is populated and output at the top of the protobuf code output.
	protoHeaderTemplate = `
// {{ .PackageName }} is generated by {{ .GeneratingBinary }} as a protobuf
// representation of a YANG schema.
//
// Input schema modules:
{{- range $inputFile := .YANGFiles }}
//  - {{ $inputFile }}
{{- end }}
// Include paths:
{{- range $importPath := .IncludePaths }}
//   - {{ $importPath }}
{{- end }}
syntax = "proto3";

package {{ .PackageName }};

import "github.com/openconfig/ygot/proto/ywrapper/ywrapper.proto";
import "github.com/openconfig/ygot/proto/yext/yext.proto";
`

	// protoMessageTemplate is populated for each entity that is mapped to a message
	// within the output protobuf.
	protoMessageTemplate = `
// {{ .Name }} represents the {{ .YANGPath }} YANG schema element.
message {{ .Name }} {
{{- range $idx, $field := .Fields }}
  {{ if $field.IsRepeated }}repeated {{ end -}}
  {{ $field.Type }} {{ $field.Name }} = {{ $field.Tag }}
  {{- $noExtensions := len .Extensions -}}
  {{- if ne $noExtensions 0 -}} [
    {{- range $i, $opt := $field.Extensions -}}
      {{- $opt -}}
      {{- if ne (inc $i) $noExtensions -}}, {{- end }}
   {{- end -}}
  ]
  {{- end -}}
  ;
{{- end }}
}`

	// protoTemplates is the set of templates that are referenced during protbuf
	// code generation.
	protoTemplates = map[string]*template.Template{
		"header": makeTemplate("header", protoHeaderTemplate),
		"msg":    makeTemplate("msg", protoMessageTemplate),
	}
)

// writeProtoMsg generates a protobuf message for the *yangDirectory described by msg.
// it uses the context of other messages to be generated (msgs), and the generator
// state stored in state to determine names of other messages. compressPaths indicates
// whether path compression should be enabled for the code generation. Returns a string
// containing the name of the package that the message is within, a string containing
// the generated code for the protobuf message, and any errors encountered during
// proto generation.
func writeProtoMsg(msg *yangDirectory, msgs map[string]*yangDirectory, state *genState, compressPaths bool) (string, string, []error) {
	msgDef, errs := genProtoMsg(msg, msgs, state, compressPaths)
	if len(errs) > 0 {
		return "", "", errs
	}

	if msg.entry.Parent == nil {
		return "", "", []error{fmt.Errorf("YANG schema element %s does not have a parent, protobuf messages are not generated for modules", msg.entry.Path())}
	}

	// pkg is the name of the protobuf package, if the entry's parent has already
	// been seen in the schema, the same package name as for siblings of this
	// entry will be returned.
	pkg := state.protobufPackage(msg.entry, compressPaths)

	var b bytes.Buffer
	if err := protoTemplates["msg"].Execute(&b, msgDef); err != nil {
		return "", "", []error{err}
	}

	return pkg, b.String(), nil

}

// genProtoMsg takes an input yangDirectory which describes a container or list entry
// within the YANG schema and returns a protoMsg which can be mapped to the protobuf
// code representing it. It uses the set of messages that have been extracted and the
// current generator state to map to other messages and ensure uniqueness of names.
func genProtoMsg(msg *yangDirectory, msgs map[string]*yangDirectory, state *genState, compressPaths bool) (protoMsg, []error) {
	var errs []error

	msgDef := protoMsg{
		// msg.name is already specified to be CamelCase in the form we expect it
		// to be for the protobuf message name.
		Name:     msg.name,
		YANGPath: slicePathToString(msg.path),
	}

	definedFieldNames := map[string]bool{}

	for name, field := range msg.fields {
		fieldDef := &protoMsgField{
			Name: makeNameUnique(safeProtoFieldName(name), definedFieldNames),
		}

		t, err := protoTagForEntry(field)
		if err != nil {
			errs = append(errs, fmt.Errorf("proto: could not generate tag for field %s: %v", field.Name, err))
		}
		fieldDef.Tag = t

		switch {
		case field.IsList():
			errs = append(errs, fmt.Errorf("proto: list generation unimplemented for %s", field.Path()))
			continue
		case field.IsDir():
			childmsg, ok := msgs[field.Path()]
			if !ok {
				errs = append(errs, fmt.Errorf("proto: could not resolve %s into a defined struct", field.Path()))
				continue
			}

			childpkg := state.protobufPackage(childmsg.entry, compressPaths)
			fieldDef.Type = fmt.Sprintf("%s.%s", childpkg, childmsg.name)
		default:
			// This is a YANG leaf, or leaf-list.
			protoType, err := state.yangTypeToProtoType(resolveTypeArgs{yangType: field.Type, contextEntry: field})
			if err != nil {
				errs = append(errs, err)
				continue
			}

			fieldDef.Type = protoType.nativeType

			if field.ListAttr != nil {
				fieldDef.IsRepeated = true
			}
		}

		msgDef.Fields = append(msgDef.Fields, fieldDef)
	}
	return msgDef, errs
}

// safeProtoFieldName takes an input string which represents the name of a YANG schema
// element and sanitises for use as a protobuf field name.
func safeProtoFieldName(name string) string {
	replacer := strings.NewReplacer(
		".", "_",
		"-", "_",
		"/", "_",
	)
	return replacer.Replace(name)
}

// fieldTag returns a protobuf tag value for the entry e. The tag value supplied is
// between 1 and 2^29-1. The values 19,000-19,999 are excluded as these are explicitly
// reserved for protobuf-internal use by https://developers.google.com/protocol-buffers/docs/proto3.
func protoTagForEntry(e *yang.Entry) (uint32, error) {
	// TODO(robjs): Replace this function with the final implementation
	// once concluded.
	return 1, nil
}
