/*
Package utestschema is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /usr/local/google/home/wenbli/gocode/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
  - ../yang/utestschema.yang
  - ../yang/refschema.yang
  - ../yang/ctestschema.yang

Imported modules were sourced from:
  - ...
*/
package utestschema

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

// UnionInt8 is an int8 type assignable to unions of which it is a subtype.
type UnionInt8 int8

// UnionInt16 is an int16 type assignable to unions of which it is a subtype.
type UnionInt16 int16

// UnionInt32 is an int32 type assignable to unions of which it is a subtype.
type UnionInt32 int32

// UnionInt64 is an int64 type assignable to unions of which it is a subtype.
type UnionInt64 int64

// UnionUint8 is a uint8 type assignable to unions of which it is a subtype.
type UnionUint8 uint8

// UnionUint16 is a uint16 type assignable to unions of which it is a subtype.
type UnionUint16 uint16

// UnionUint32 is a uint32 type assignable to unions of which it is a subtype.
type UnionUint32 uint32

// UnionUint64 is a uint64 type assignable to unions of which it is a subtype.
type UnionUint64 uint64

// UnionFloat64 is a float64 type assignable to unions of which it is a subtype.
type UnionFloat64 float64

// UnionString is a string type assignable to unions of which it is a subtype.
type UnionString string

// UnionBool is a bool type assignable to unions of which it is a subtype.
type UnionBool bool

// UnionUnsupported is an interface{} wrapper type for unsupported types. It is
// assignable to unions of which it is a subtype.
type UnionUnsupported struct {
	Value interface{}
}

var (
	SchemaTree map[string]*yang.Entry
	ΛEnumTypes map[string][]reflect.Type
)

func init() {
	var err error
	initΛEnumTypes()
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " + err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root:       &Device{},
		SchemaTree: uzp,
		Unmarshal:  Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn)
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Ctestschema_OrderedLists represents the /ctestschema/ordered-lists YANG schema element.
type Ctestschema_OrderedLists struct {
	ΛMetadata    []ygot.Annotation                               `path:"@" ygotAnnotation:"true"`
	OrderedList  Ctestschema_OrderedLists_OrderedList_OrderedMap `path:"ordered-list" module:"ctestschema"`
	ΛOrderedList []ygot.Annotation                               `path:"@ordered-list" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedLists implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedLists) IsYANGGoStruct() {}

type Ctestschema_OrderedLists_OrderedList_OrderedMap struct {
	keys     []string
	valueMap map[string]*Ctestschema_OrderedLists_OrderedList
}

// IsYANGGoStruct ensures that Ctestschema_OrderedLists_OrderedList_OrderedMap implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedLists_OrderedList_OrderedMap) IsYANGGoStruct() {}

// init initializes any uninitialized values.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) init() {
	if o.valueMap == nil {
		o.valueMap = map[string]*Ctestschema_OrderedLists_OrderedList{}
	}
}

// Keys returns a copy of the list's keys.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Keys() []string {
	return append([]string{}, o.keys...)
}

// Values returns the current set of the list's values in order.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Values() []*Ctestschema_OrderedLists_OrderedList {
	var values []*Ctestschema_OrderedLists_OrderedList
	for _, key := range o.keys {
		values = append(values, o.valueMap[key])
	}
	return values
}

// Len returns a size of Ctestschema_OrderedLists_OrderedList_OrderedMap
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Len() int {
	return len(o.keys)
}

// Get returns the value corresponding to the key. If the key is not found, nil
// is returned.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Get(key string) *Ctestschema_OrderedLists_OrderedList {
	val, _ := o.valueMap[key]
	return val
}

// Delete deletes an element.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Delete(key string) bool {
	if _, ok := o.valueMap[key]; !ok {
		return false
	}
	for i, k := range o.keys {
		if k == key {
			o.keys = append(o.keys[:i], o.keys[i+1:]...)
			delete(o.valueMap, key)
			return true
		}
	}
	return false
}

// Append appends a Ctestschema_OrderedLists_OrderedList, returning an error if the key
// already exists in the ordered list or if the key is unspecified.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) Append(v *Ctestschema_OrderedLists_OrderedList) error {
	if v == nil {
		return fmt.Errorf("nil Ctestschema_OrderedLists_OrderedList")
	}
	if v.Key == nil {
		return fmt.Errorf("invalid nil key received for Key")
	}

	key := *v.Key

	if _, ok := o.valueMap[key]; ok {
		return fmt.Errorf("duplicate key for list Statement %v", key)
	}
	o.keys = append(o.keys, key)
	o.init()
	o.valueMap[key] = v
	return nil
}

// AppendNew creates and appends a new Ctestschema_OrderedLists_OrderedList, returning the
// newly-initialized v. It returns an error if the v already exists.
func (o *Ctestschema_OrderedLists_OrderedList_OrderedMap) AppendNew(Key string) (*Ctestschema_OrderedLists_OrderedList, error) {
	key := Key

	if _, ok := o.valueMap[key]; ok {
		return nil, fmt.Errorf("duplicate key for list Statement %v", key)
	}
	o.keys = append(o.keys, key)
	newElement := &Ctestschema_OrderedLists_OrderedList{
		Key: &Key,
	}
	o.init()
	o.valueMap[key] = newElement
	return newElement, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedLists"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedLists) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedLists.
func (*Ctestschema_OrderedLists) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedLists_OrderedList represents the /ctestschema/ordered-lists/ordered-list YANG schema element.
type Ctestschema_OrderedLists_OrderedList struct {
	ΛMetadata []ygot.Annotation                            `path:"@" ygotAnnotation:"true"`
	Config    *Ctestschema_OrderedLists_OrderedList_Config `path:"config" module:"ctestschema"`
	ΛConfig   []ygot.Annotation                            `path:"@config" ygotAnnotation:"true"`
	Key       *string                                      `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation                            `path:"@key" ygotAnnotation:"true"`
	State     *Ctestschema_OrderedLists_OrderedList_State  `path:"state" module:"ctestschema"`
	ΛState    []ygot.Annotation                            `path:"@state" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedLists_OrderedList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedLists_OrderedList) IsYANGGoStruct() {}

// GetOrCreateConfig retrieves the value of the Config field
// or returns the existing field if it already exists.
func (t *Ctestschema_OrderedLists_OrderedList) GetOrCreateConfig() *Ctestschema_OrderedLists_OrderedList_Config {
	if t.Config != nil {
		return t.Config
	}
	t.Config = &Ctestschema_OrderedLists_OrderedList_Config{}
	return t.Config
}

// GetOrCreateState retrieves the value of the State field
// or returns the existing field if it already exists.
func (t *Ctestschema_OrderedLists_OrderedList) GetOrCreateState() *Ctestschema_OrderedLists_OrderedList_State {
	if t.State != nil {
		return t.State
	}
	t.State = &Ctestschema_OrderedLists_OrderedList_State{}
	return t.State
}

// GetConfig returns the value of the Config struct pointer
// from Ctestschema_OrderedLists_OrderedList. If the receiver or the field Config is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_OrderedLists_OrderedList) GetConfig() *Ctestschema_OrderedLists_OrderedList_Config {
	if t != nil && t.Config != nil {
		return t.Config
	}
	return nil
}

// GetState returns the value of the State struct pointer
// from Ctestschema_OrderedLists_OrderedList. If the receiver or the field State is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_OrderedLists_OrderedList) GetState() *Ctestschema_OrderedLists_OrderedList_State {
	if t != nil && t.State != nil {
		return t.State
	}
	return nil
}

// GetKey retrieves the value of the leaf Key from the Ctestschema_OrderedLists_OrderedList
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedLists_OrderedList) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// ΛListKeyMap returns the keys of the Ctestschema_OrderedLists_OrderedList struct, which is a YANG list entry.
func (t *Ctestschema_OrderedLists_OrderedList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Key == nil {
		return nil, fmt.Errorf("nil value for key Key")
	}

	return map[string]interface{}{
		"key": *t.Key,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedLists_OrderedList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedLists_OrderedList) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedLists_OrderedList.
func (*Ctestschema_OrderedLists_OrderedList) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedLists_OrderedList_Config represents the /ctestschema/ordered-lists/ordered-list/config YANG schema element.
type Ctestschema_OrderedLists_OrderedList_Config struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key       *string           `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation `path:"@key" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedLists_OrderedList_Config implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedLists_OrderedList_Config) IsYANGGoStruct() {}

// GetKey retrieves the value of the leaf Key from the Ctestschema_OrderedLists_OrderedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedLists_OrderedList_Config) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_OrderedLists_OrderedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedLists_OrderedList_Config) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList_Config) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedLists_OrderedList_Config"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList_Config) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedLists_OrderedList_Config) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedLists_OrderedList_Config.
func (*Ctestschema_OrderedLists_OrderedList_Config) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedLists_OrderedList_State represents the /ctestschema/ordered-lists/ordered-list/state YANG schema element.
type Ctestschema_OrderedLists_OrderedList_State struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key       *string           `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation `path:"@key" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedLists_OrderedList_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedLists_OrderedList_State) IsYANGGoStruct() {}

// GetKey retrieves the value of the leaf Key from the Ctestschema_OrderedLists_OrderedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedLists_OrderedList_State) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_OrderedLists_OrderedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedLists_OrderedList_State) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList_State) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedLists_OrderedList_State"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedLists_OrderedList_State) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedLists_OrderedList_State) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedLists_OrderedList_State.
func (*Ctestschema_OrderedLists_OrderedList_State) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedMultikeyedLists represents the /ctestschema/ordered-multikeyed-lists YANG schema element.
type Ctestschema_OrderedMultikeyedLists struct {
	ΛMetadata              []ygot.Annotation                                                   `path:"@" ygotAnnotation:"true"`
	OrderedMultikeyedList  Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap `path:"ordered-multikeyed-list" module:"ctestschema"`
	ΛOrderedMultikeyedList []ygot.Annotation                                                   `path:"@ordered-multikeyed-list" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedMultikeyedLists implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedMultikeyedLists) IsYANGGoStruct() {}

// Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key represents the key for list OrderedMultikeyedList of element /ctestschema/ordered-multikeyed-lists.
type Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key struct {
	Key1 string `path:"key1"`
	Key2 uint64 `path:"key2"`
}

// IsYANGGoKeyStruct ensures that Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key partially implements the
// yang.GoKeyStruct interface. This allows functions that need to
// handle this key struct to identify it as being generated by gogen.
func (Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key) IsYANGGoKeyStruct() {}

// ΛListKeyMap returns the values of the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key key struct.
func (t Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key) ΛListKeyMap() (map[string]interface{}, error) {
	return map[string]interface{}{
		"key1": t.Key1,
		"key2": t.Key2,
	}, nil
}

type Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap struct {
	keys     []Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key
	valueMap map[Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key]*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList
}

// IsYANGGoStruct ensures that Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) IsYANGGoStruct() {}

// init initializes any uninitialized values.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) init() {
	if o.valueMap == nil {
		o.valueMap = map[Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key]*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList{}
	}
}

// Keys returns a copy of the list's keys.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Keys() []Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key {
	return append([]Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key{}, o.keys...)
}

// Values returns the current set of the list's values in order.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Values() []*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList {
	var values []*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList
	for _, key := range o.keys {
		values = append(values, o.valueMap[key])
	}
	return values
}

// Len returns a size of Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Len() int {
	return len(o.keys)
}

// Get returns the value corresponding to the key. If the key is not found, nil
// is returned.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Get(key Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key) *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList {
	val, _ := o.valueMap[key]
	return val
}

// Delete deletes an element.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Delete(key Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key) bool {
	if _, ok := o.valueMap[key]; !ok {
		return false
	}
	for i, k := range o.keys {
		if k == key {
			o.keys = append(o.keys[:i], o.keys[i+1:]...)
			delete(o.valueMap, key)
			return true
		}
	}
	return false
}

// Append appends a Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList, returning an error if the key
// already exists in the ordered list or if the key is unspecified.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) Append(v *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) error {
	if v == nil {
		return fmt.Errorf("nil Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList")
	}
	if v.Key1 == nil {
		return fmt.Errorf("invalid nil key for Key1")
	}
	if v.Key2 == nil {
		return fmt.Errorf("invalid nil key for Key2")
	}
	key := Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key{
		Key1: *v.Key1,
		Key2: *v.Key2,
	}

	if _, ok := o.valueMap[key]; ok {
		return fmt.Errorf("duplicate key for list Statement %v", key)
	}
	o.keys = append(o.keys, key)
	o.init()
	o.valueMap[key] = v
	return nil
}

// AppendNew creates and appends a new Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList, returning the
// newly-initialized v. It returns an error if the v already exists.
func (o *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_OrderedMap) AppendNew(Key1 string, Key2 uint64) (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList, error) {
	key := Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Key{
		Key1: Key1,
		Key2: Key2,
	}

	if _, ok := o.valueMap[key]; ok {
		return nil, fmt.Errorf("duplicate key for list Statement %v", key)
	}
	o.keys = append(o.keys, key)
	newElement := &Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList{
		Key1: &Key1,
		Key2: &Key2,
	}
	o.init()
	o.valueMap[key] = newElement
	return newElement, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedMultikeyedLists"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedMultikeyedLists) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedMultikeyedLists.
func (*Ctestschema_OrderedMultikeyedLists) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList represents the /ctestschema/ordered-multikeyed-lists/ordered-multikeyed-list YANG schema element.
type Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList struct {
	ΛMetadata []ygot.Annotation                                                `path:"@" ygotAnnotation:"true"`
	Config    *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config `path:"config" module:"ctestschema"`
	ΛConfig   []ygot.Annotation                                                `path:"@config" ygotAnnotation:"true"`
	Key1      *string                                                          `path:"key1" module:"ctestschema"`
	ΛKey1     []ygot.Annotation                                                `path:"@key1" ygotAnnotation:"true"`
	Key2      *uint64                                                          `path:"key2" module:"ctestschema"`
	ΛKey2     []ygot.Annotation                                                `path:"@key2" ygotAnnotation:"true"`
	State     *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State  `path:"state" module:"ctestschema"`
	ΛState    []ygot.Annotation                                                `path:"@state" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) IsYANGGoStruct() {}

// GetOrCreateConfig retrieves the value of the Config field
// or returns the existing field if it already exists.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetOrCreateConfig() *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config {
	if t.Config != nil {
		return t.Config
	}
	t.Config = &Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config{}
	return t.Config
}

// GetOrCreateState retrieves the value of the State field
// or returns the existing field if it already exists.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetOrCreateState() *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State {
	if t.State != nil {
		return t.State
	}
	t.State = &Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State{}
	return t.State
}

// GetConfig returns the value of the Config struct pointer
// from Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList. If the receiver or the field Config is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetConfig() *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config {
	if t != nil && t.Config != nil {
		return t.Config
	}
	return nil
}

// GetState returns the value of the State struct pointer
// from Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList. If the receiver or the field State is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetState() *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State {
	if t != nil && t.State != nil {
		return t.State
	}
	return nil
}

// GetKey1 retrieves the value of the leaf Key1 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key1 is set, it can
// safely use t.GetKey1() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key1 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetKey1() string {
	if t == nil || t.Key1 == nil {
		return ""
	}
	return *t.Key1
}

// GetKey2 retrieves the value of the leaf Key2 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key2 is set, it can
// safely use t.GetKey2() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key2 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) GetKey2() uint64 {
	if t == nil || t.Key2 == nil {
		return 0
	}
	return *t.Key2
}

// ΛListKeyMap returns the keys of the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList struct, which is a YANG list entry.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Key1 == nil {
		return nil, fmt.Errorf("nil value for key Key1")
	}

	if t.Key2 == nil {
		return nil, fmt.Errorf("nil value for key Key2")
	}

	return map[string]interface{}{
		"key1": *t.Key1,
		"key2": *t.Key2,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config represents the /ctestschema/ordered-multikeyed-lists/ordered-multikeyed-list/config YANG schema element.
type Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key1      *string           `path:"key1" module:"ctestschema"`
	ΛKey1     []ygot.Annotation `path:"@key1" ygotAnnotation:"true"`
	Key2      *uint64           `path:"key2" module:"ctestschema"`
	ΛKey2     []ygot.Annotation `path:"@key2" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) IsYANGGoStruct() {}

// GetKey1 retrieves the value of the leaf Key1 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key1 is set, it can
// safely use t.GetKey1() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key1 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) GetKey1() string {
	if t == nil || t.Key1 == nil {
		return ""
	}
	return *t.Key1
}

// GetKey2 retrieves the value of the leaf Key2 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key2 is set, it can
// safely use t.GetKey2() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key2 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) GetKey2() uint64 {
	if t == nil || t.Key2 == nil {
		return 0
	}
	return *t.Key2
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_Config) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State represents the /ctestschema/ordered-multikeyed-lists/ordered-multikeyed-list/state YANG schema element.
type Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key1      *string           `path:"key1" module:"ctestschema"`
	ΛKey1     []ygot.Annotation `path:"@key1" ygotAnnotation:"true"`
	Key2      *uint64           `path:"key2" module:"ctestschema"`
	ΛKey2     []ygot.Annotation `path:"@key2" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) IsYANGGoStruct() {}

// GetKey1 retrieves the value of the leaf Key1 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key1 is set, it can
// safely use t.GetKey1() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key1 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) GetKey1() string {
	if t == nil || t.Key1 == nil {
		return ""
	}
	return *t.Key1
}

// GetKey2 retrieves the value of the leaf Key2 from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key2 is set, it can
// safely use t.GetKey2() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key2 == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) GetKey2() uint64 {
	if t == nil || t.Key2 == nil {
		return 0
	}
	return *t.Key2
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State.
func (*Ctestschema_OrderedMultikeyedLists_OrderedMultikeyedList_State) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_UnorderedLists represents the /ctestschema/unordered-lists YANG schema element.
type Ctestschema_UnorderedLists struct {
	ΛMetadata      []ygot.Annotation                                    `path:"@" ygotAnnotation:"true"`
	UnorderedList  map[string]*Ctestschema_UnorderedLists_UnorderedList `path:"unordered-list" module:"ctestschema"`
	ΛUnorderedList []ygot.Annotation                                    `path:"@unordered-list" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_UnorderedLists implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_UnorderedLists) IsYANGGoStruct() {}

// NewUnorderedList creates a new entry in the UnorderedList list of the
// Ctestschema_UnorderedLists struct. The keys of the list are populated from the input
// arguments.
func (t *Ctestschema_UnorderedLists) NewUnorderedList(Key string) (*Ctestschema_UnorderedLists_UnorderedList, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.UnorderedList == nil {
		t.UnorderedList = make(map[string]*Ctestschema_UnorderedLists_UnorderedList)
	}

	key := Key

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.UnorderedList[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list UnorderedList", key)
	}

	t.UnorderedList[key] = &Ctestschema_UnorderedLists_UnorderedList{
		Key: &Key,
	}

	return t.UnorderedList[key], nil
}

// RenameUnorderedList renames an entry in the list UnorderedList within
// the Ctestschema_UnorderedLists struct. The entry with key oldK is renamed to newK updating
// the key within the value.
func (t *Ctestschema_UnorderedLists) RenameUnorderedList(oldK, newK string) error {
	if _, ok := t.UnorderedList[newK]; ok {
		return fmt.Errorf("key %v already exists in UnorderedList", newK)
	}

	e, ok := t.UnorderedList[oldK]
	if !ok {
		return fmt.Errorf("key %v not found in UnorderedList", oldK)
	}
	e.Key = &newK

	t.UnorderedList[newK] = e
	delete(t.UnorderedList, oldK)
	return nil
}

// GetOrCreateUnorderedList retrieves the value with the specified keys from
// the receiver Ctestschema_UnorderedLists. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Ctestschema_UnorderedLists) GetOrCreateUnorderedList(Key string) *Ctestschema_UnorderedLists_UnorderedList {

	key := Key

	if v, ok := t.UnorderedList[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewUnorderedList(Key)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateUnorderedList got unexpected error: %v", err))
	}
	return v
}

// GetUnorderedList retrieves the value with the specified key from
// the UnorderedList map field of Ctestschema_UnorderedLists. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Ctestschema_UnorderedLists) GetUnorderedList(Key string) *Ctestschema_UnorderedLists_UnorderedList {

	if t == nil {
		return nil
	}

	key := Key

	if lm, ok := t.UnorderedList[key]; ok {
		return lm
	}
	return nil
}

// AppendUnorderedList appends the supplied Ctestschema_UnorderedLists_UnorderedList struct to the
// list UnorderedList of Ctestschema_UnorderedLists. If the key value(s) specified in
// the supplied Ctestschema_UnorderedLists_UnorderedList already exist in the list, an error is
// returned.
func (t *Ctestschema_UnorderedLists) AppendUnorderedList(v *Ctestschema_UnorderedLists_UnorderedList) error {
	if v.Key == nil {
		return fmt.Errorf("invalid nil key received for Key")
	}

	key := *v.Key

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.UnorderedList == nil {
		t.UnorderedList = make(map[string]*Ctestschema_UnorderedLists_UnorderedList)
	}

	if _, ok := t.UnorderedList[key]; ok {
		return fmt.Errorf("duplicate key for list UnorderedList %v", key)
	}

	t.UnorderedList[key] = v
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_UnorderedLists"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_UnorderedLists) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_UnorderedLists.
func (*Ctestschema_UnorderedLists) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_UnorderedLists_UnorderedList represents the /ctestschema/unordered-lists/unordered-list YANG schema element.
type Ctestschema_UnorderedLists_UnorderedList struct {
	ΛMetadata []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	Config    *Ctestschema_UnorderedLists_UnorderedList_Config `path:"config" module:"ctestschema"`
	ΛConfig   []ygot.Annotation                                `path:"@config" ygotAnnotation:"true"`
	Key       *string                                          `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation                                `path:"@key" ygotAnnotation:"true"`
	State     *Ctestschema_UnorderedLists_UnorderedList_State  `path:"state" module:"ctestschema"`
	ΛState    []ygot.Annotation                                `path:"@state" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_UnorderedLists_UnorderedList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_UnorderedLists_UnorderedList) IsYANGGoStruct() {}

// GetOrCreateConfig retrieves the value of the Config field
// or returns the existing field if it already exists.
func (t *Ctestschema_UnorderedLists_UnorderedList) GetOrCreateConfig() *Ctestschema_UnorderedLists_UnorderedList_Config {
	if t.Config != nil {
		return t.Config
	}
	t.Config = &Ctestschema_UnorderedLists_UnorderedList_Config{}
	return t.Config
}

// GetOrCreateState retrieves the value of the State field
// or returns the existing field if it already exists.
func (t *Ctestschema_UnorderedLists_UnorderedList) GetOrCreateState() *Ctestschema_UnorderedLists_UnorderedList_State {
	if t.State != nil {
		return t.State
	}
	t.State = &Ctestschema_UnorderedLists_UnorderedList_State{}
	return t.State
}

// GetConfig returns the value of the Config struct pointer
// from Ctestschema_UnorderedLists_UnorderedList. If the receiver or the field Config is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_UnorderedLists_UnorderedList) GetConfig() *Ctestschema_UnorderedLists_UnorderedList_Config {
	if t != nil && t.Config != nil {
		return t.Config
	}
	return nil
}

// GetState returns the value of the State struct pointer
// from Ctestschema_UnorderedLists_UnorderedList. If the receiver or the field State is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Ctestschema_UnorderedLists_UnorderedList) GetState() *Ctestschema_UnorderedLists_UnorderedList_State {
	if t != nil && t.State != nil {
		return t.State
	}
	return nil
}

// GetKey retrieves the value of the leaf Key from the Ctestschema_UnorderedLists_UnorderedList
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_UnorderedLists_UnorderedList) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// ΛListKeyMap returns the keys of the Ctestschema_UnorderedLists_UnorderedList struct, which is a YANG list entry.
func (t *Ctestschema_UnorderedLists_UnorderedList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Key == nil {
		return nil, fmt.Errorf("nil value for key Key")
	}

	return map[string]interface{}{
		"key": *t.Key,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_UnorderedLists_UnorderedList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_UnorderedLists_UnorderedList) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_UnorderedLists_UnorderedList.
func (*Ctestschema_UnorderedLists_UnorderedList) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_UnorderedLists_UnorderedList_Config represents the /ctestschema/unordered-lists/unordered-list/config YANG schema element.
type Ctestschema_UnorderedLists_UnorderedList_Config struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key       *string           `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation `path:"@key" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_UnorderedLists_UnorderedList_Config implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_UnorderedLists_UnorderedList_Config) IsYANGGoStruct() {}

// GetKey retrieves the value of the leaf Key from the Ctestschema_UnorderedLists_UnorderedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_UnorderedLists_UnorderedList_Config) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_UnorderedLists_UnorderedList_Config
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_UnorderedLists_UnorderedList_Config) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList_Config) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_UnorderedLists_UnorderedList_Config"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList_Config) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_UnorderedLists_UnorderedList_Config) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_UnorderedLists_UnorderedList_Config.
func (*Ctestschema_UnorderedLists_UnorderedList_Config) ΛBelongingModule() string {
	return "ctestschema"
}

// Ctestschema_UnorderedLists_UnorderedList_State represents the /ctestschema/unordered-lists/unordered-list/state YANG schema element.
type Ctestschema_UnorderedLists_UnorderedList_State struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Key       *string           `path:"key" module:"ctestschema"`
	ΛKey      []ygot.Annotation `path:"@key" ygotAnnotation:"true"`
	Value     *string           `path:"value" module:"ctestschema"`
	ΛValue    []ygot.Annotation `path:"@value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Ctestschema_UnorderedLists_UnorderedList_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Ctestschema_UnorderedLists_UnorderedList_State) IsYANGGoStruct() {}

// GetKey retrieves the value of the leaf Key from the Ctestschema_UnorderedLists_UnorderedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Key is set, it can
// safely use t.GetKey() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Key == nil' before retrieving the leaf's value.
func (t *Ctestschema_UnorderedLists_UnorderedList_State) GetKey() string {
	if t == nil || t.Key == nil {
		return ""
	}
	return *t.Key
}

// GetValue retrieves the value of the leaf Value from the Ctestschema_UnorderedLists_UnorderedList_State
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Value is set, it can
// safely use t.GetValue() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Value == nil' before retrieving the leaf's value.
func (t *Ctestschema_UnorderedLists_UnorderedList_State) GetValue() string {
	if t == nil || t.Value == nil {
		return ""
	}
	return *t.Value
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList_State) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Ctestschema_UnorderedLists_UnorderedList_State"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Ctestschema_UnorderedLists_UnorderedList_State) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Ctestschema_UnorderedLists_UnorderedList_State) ΛEnumTypeMap() map[string][]reflect.Type {
	return ΛEnumTypes
}

// ΛBelongingModule returns the name of the module that defines the namespace
// of Ctestschema_UnorderedLists_UnorderedList_State.
func (*Ctestschema_UnorderedLists_UnorderedList_State) ΛBelongingModule() string {
	return "ctestschema"
}

// Device represents the /device YANG schema element.
type Device struct {
	ΛMetadata               []ygot.Annotation                   `path:"@" ygotAnnotation:"true"`
	OrderedLists            *Ctestschema_OrderedLists           `path:"ordered-lists" module:"ctestschema"`
	ΛOrderedLists           []ygot.Annotation                   `path:"@ordered-lists" ygotAnnotation:"true"`
	OrderedMultikeyedLists  *Ctestschema_OrderedMultikeyedLists `path:"ordered-multikeyed-lists" module:"ctestschema"`
	ΛOrderedMultikeyedLists []ygot.Annotation                   `path:"@ordered-multikeyed-lists" ygotAnnotation:"true"`
	Ref                     *Refschema_Ref                      `path:"ref" module:"refschema"`
	ΛRef                    []ygot.Annotation                   `path:"@ref" ygotAnnotation:"true"`
	Target                  *Utestschema_Target                 `path:"target" module:"utestschema"`
	ΛTarget                 []ygot.Annotation                   `path:"@target" ygotAnnotation:"true"`
	UnorderedLists          *Ctestschema_UnorderedLists         `path:"unordered-lists" module:"ctestschema"`
	ΛUnorderedLists         []ygot.Annotation                   `path:"@unordered-lists" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// GetOrCreateOrderedLists retrieves the value of the OrderedLists field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateOrderedLists() *Ctestschema_OrderedLists {
	if t.OrderedLists != nil {
		return t.OrderedLists
	}
	t.OrderedLists = &Ctestschema_OrderedLists{}
	return t.OrderedLists
}

// GetOrCreateOrderedMultikeyedLists retrieves the value of the OrderedMultikeyedLists field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateOrderedMultikeyedLists() *Ctestschema_OrderedMultikeyedLists {
	if t.OrderedMultikeyedLists != nil {
		return t.OrderedMultikeyedLists
	}
	t.OrderedMultikeyedLists = &Ctestschema_OrderedMultikeyedLists{}
	return t.OrderedMultikeyedLists
}

// GetOrCreateRef retrieves the value of the Ref field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateRef() *Refschema_Ref {
	if t.Ref != nil {
		return t.Ref
	}
	t.Ref = &Refschema_Ref{}
	return t.Ref
}

// GetOrCreateTarget retrieves the value of the Target field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateTarget() *Utestschema_Target {
	if t.Target != nil {
		return t.Target
	}
	t.Target = &Utestschema_Target{}
	return t.Target
}

// GetOrCreateUnorderedLists retrieves the value of the UnorderedLists field
// or returns the existing field if it already exists.
func (t *Device) GetOrCreateUnorderedLists() *Ctestschema_UnorderedLists {
	if t.UnorderedLists != nil {
		return t.UnorderedLists
	}
	t.UnorderedLists = &Ctestschema_UnorderedLists{}
	return t.UnorderedLists
}

// GetOrderedLists returns the value of the OrderedLists struct pointer
// from Device. If the receiver or the field OrderedLists is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetOrderedLists() *Ctestschema_OrderedLists {
	if t != nil && t.OrderedLists != nil {
		return t.OrderedLists
	}
	return nil
}

// GetOrderedMultikeyedLists returns the value of the OrderedMultikeyedLists struct pointer
// from Device. If the receiver or the field OrderedMultikeyedLists is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetOrderedMultikeyedLists() *Ctestschema_OrderedMultikeyedLists {
	if t != nil && t.OrderedMultikeyedLists != nil {
		return t.OrderedMultikeyedLists
	}
	return nil
}

// GetRef returns the value of the Ref struct pointer
// from Device. If the receiver or the field Ref is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetRef() *Refschema_Ref {
	if t != nil && t.Ref != nil {
		return t.Ref
	}
	return nil
}

// GetTarget returns the value of the Target struct pointer
// from Device. If the receiver or the field Target is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetTarget() *Utestschema_Target {
	if t != nil && t.Target != nil {
		return t.Target
	}
	return nil
}

// GetUnorderedLists returns the value of the UnorderedLists struct pointer
// from Device. If the receiver or the field UnorderedLists is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *Device) GetUnorderedLists() *Ctestschema_UnorderedLists {
	if t != nil && t.UnorderedLists != nil {
		return t.UnorderedLists
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Device.
func (*Device) ΛBelongingModule() string {
	return ""
}

// Refschema_Ref represents the /refschema/ref YANG schema element.
type Refschema_Ref struct {
	ΛMetadata  []ygot.Annotation                   `path:"@" ygotAnnotation:"true"`
	Reference  map[string]*Refschema_Ref_Reference `path:"reference" module:"refschema"`
	ΛReference []ygot.Annotation                   `path:"@reference" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Refschema_Ref implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Refschema_Ref) IsYANGGoStruct() {}

// NewReference creates a new entry in the Reference list of the
// Refschema_Ref struct. The keys of the list are populated from the input
// arguments.
func (t *Refschema_Ref) NewReference(Name string) (*Refschema_Ref_Reference, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Reference == nil {
		t.Reference = make(map[string]*Refschema_Ref_Reference)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Reference[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Reference", key)
	}

	t.Reference[key] = &Refschema_Ref_Reference{
		Name: &Name,
	}

	return t.Reference[key], nil
}

// RenameReference renames an entry in the list Reference within
// the Refschema_Ref struct. The entry with key oldK is renamed to newK updating
// the key within the value.
func (t *Refschema_Ref) RenameReference(oldK, newK string) error {
	if _, ok := t.Reference[newK]; ok {
		return fmt.Errorf("key %v already exists in Reference", newK)
	}

	e, ok := t.Reference[oldK]
	if !ok {
		return fmt.Errorf("key %v not found in Reference", oldK)
	}
	e.Name = &newK

	t.Reference[newK] = e
	delete(t.Reference, oldK)
	return nil
}

// GetOrCreateReference retrieves the value with the specified keys from
// the receiver Refschema_Ref. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Refschema_Ref) GetOrCreateReference(Name string) *Refschema_Ref_Reference {

	key := Name

	if v, ok := t.Reference[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewReference(Name)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateReference got unexpected error: %v", err))
	}
	return v
}

// GetReference retrieves the value with the specified key from
// the Reference map field of Refschema_Ref. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Refschema_Ref) GetReference(Name string) *Refschema_Ref_Reference {

	if t == nil {
		return nil
	}

	key := Name

	if lm, ok := t.Reference[key]; ok {
		return lm
	}
	return nil
}

// AppendReference appends the supplied Refschema_Ref_Reference struct to the
// list Reference of Refschema_Ref. If the key value(s) specified in
// the supplied Refschema_Ref_Reference already exist in the list, an error is
// returned.
func (t *Refschema_Ref) AppendReference(v *Refschema_Ref_Reference) error {
	if v.Name == nil {
		return fmt.Errorf("invalid nil key received for Name")
	}

	key := *v.Name

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Reference == nil {
		t.Reference = make(map[string]*Refschema_Ref_Reference)
	}

	if _, ok := t.Reference[key]; ok {
		return fmt.Errorf("duplicate key for list Reference %v", key)
	}

	t.Reference[key] = v
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Refschema_Ref) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Refschema_Ref"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Refschema_Ref) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Refschema_Ref) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Refschema_Ref.
func (*Refschema_Ref) ΛBelongingModule() string {
	return "refschema"
}

// Refschema_Ref_Reference represents the /refschema/ref/reference YANG schema element.
type Refschema_Ref_Reference struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Name      *string           `path:"name" module:"refschema"`
	ΛName     []ygot.Annotation `path:"@name" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Refschema_Ref_Reference implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Refschema_Ref_Reference) IsYANGGoStruct() {}

// GetName retrieves the value of the leaf Name from the Refschema_Ref_Reference
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Name is set, it can
// safely use t.GetName() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Name == nil' before retrieving the leaf's value.
func (t *Refschema_Ref_Reference) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// ΛListKeyMap returns the keys of the Refschema_Ref_Reference struct, which is a YANG list entry.
func (t *Refschema_Ref_Reference) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Refschema_Ref_Reference) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Refschema_Ref_Reference"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Refschema_Ref_Reference) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Refschema_Ref_Reference) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Refschema_Ref_Reference.
func (*Refschema_Ref_Reference) ΛBelongingModule() string {
	return "refschema"
}

// Utestschema_Target represents the /utestschema/target YANG schema element.
type Utestschema_Target struct {
	ΛMetadata []ygot.Annotation                     `path:"@" ygotAnnotation:"true"`
	Entity    map[string]*Utestschema_Target_Entity `path:"entity" module:"utestschema"`
	ΛEntity   []ygot.Annotation                     `path:"@entity" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Utestschema_Target implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Utestschema_Target) IsYANGGoStruct() {}

// NewEntity creates a new entry in the Entity list of the
// Utestschema_Target struct. The keys of the list are populated from the input
// arguments.
func (t *Utestschema_Target) NewEntity(Name string) (*Utestschema_Target_Entity, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Entity == nil {
		t.Entity = make(map[string]*Utestschema_Target_Entity)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Entity[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Entity", key)
	}

	t.Entity[key] = &Utestschema_Target_Entity{
		Name: &Name,
	}

	return t.Entity[key], nil
}

// RenameEntity renames an entry in the list Entity within
// the Utestschema_Target struct. The entry with key oldK is renamed to newK updating
// the key within the value.
func (t *Utestschema_Target) RenameEntity(oldK, newK string) error {
	if _, ok := t.Entity[newK]; ok {
		return fmt.Errorf("key %v already exists in Entity", newK)
	}

	e, ok := t.Entity[oldK]
	if !ok {
		return fmt.Errorf("key %v not found in Entity", oldK)
	}
	e.Name = &newK

	t.Entity[newK] = e
	delete(t.Entity, oldK)
	return nil
}

// GetOrCreateEntity retrieves the value with the specified keys from
// the receiver Utestschema_Target. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Utestschema_Target) GetOrCreateEntity(Name string) *Utestschema_Target_Entity {

	key := Name

	if v, ok := t.Entity[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewEntity(Name)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateEntity got unexpected error: %v", err))
	}
	return v
}

// GetEntity retrieves the value with the specified key from
// the Entity map field of Utestschema_Target. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Utestschema_Target) GetEntity(Name string) *Utestschema_Target_Entity {

	if t == nil {
		return nil
	}

	key := Name

	if lm, ok := t.Entity[key]; ok {
		return lm
	}
	return nil
}

// AppendEntity appends the supplied Utestschema_Target_Entity struct to the
// list Entity of Utestschema_Target. If the key value(s) specified in
// the supplied Utestschema_Target_Entity already exist in the list, an error is
// returned.
func (t *Utestschema_Target) AppendEntity(v *Utestschema_Target_Entity) error {
	if v.Name == nil {
		return fmt.Errorf("invalid nil key received for Name")
	}

	key := *v.Name

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Entity == nil {
		t.Entity = make(map[string]*Utestschema_Target_Entity)
	}

	if _, ok := t.Entity[key]; ok {
		return fmt.Errorf("duplicate key for list Entity %v", key)
	}

	t.Entity[key] = v
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Utestschema_Target) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Utestschema_Target"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Utestschema_Target) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Utestschema_Target) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Utestschema_Target.
func (*Utestschema_Target) ΛBelongingModule() string {
	return "utestschema"
}

// Utestschema_Target_Entity represents the /utestschema/target/entity YANG schema element.
type Utestschema_Target_Entity struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Name      *string           `path:"name" module:"utestschema"`
	ΛName     []ygot.Annotation `path:"@name" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Utestschema_Target_Entity implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Utestschema_Target_Entity) IsYANGGoStruct() {}

// GetName retrieves the value of the leaf Name from the Utestschema_Target_Entity
// struct. If the field is unset but has a default value in the YANG schema,
// then the default value will be returned.
// Caution should be exercised whilst using this method since when without a
// default value, it will return the Go zero value if the field is explicitly
// unset. If the caller explicitly does not care if Name is set, it can
// safely use t.GetName() to retrieve the value. In the case that the
// caller has different actions based on whether the leaf is set or unset, it
// should use 'if t.Name == nil' before retrieving the leaf's value.
func (t *Utestschema_Target_Entity) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// ΛListKeyMap returns the keys of the Utestschema_Target_Entity struct, which is a YANG list entry.
func (t *Utestschema_Target_Entity) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Utestschema_Target_Entity) ΛValidate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Utestschema_Target_Entity"], t, opts...); err != nil {
		return err
	}
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Utestschema_Target_Entity) Validate(opts ...ygot.ValidationOption) error {
	return t.ΛValidate(opts...)
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Utestschema_Target_Entity) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module that defines the namespace
// of Utestschema_Target_Entity.
func (*Utestschema_Target_Entity) ΛBelongingModule() string {
	return "utestschema"
}

var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5d, 0xdd, 0x6f, 0xdb, 0x36,
		0x10, 0x7f, 0xf7, 0x5f, 0x21, 0xe8, 0x39, 0xad, 0x2d, 0xcf, 0xf9, 0x98, 0xdf, 0xb2, 0xa6, 0xc5,
		0x80, 0x2e, 0x5b, 0x91, 0x36, 0x7b, 0x19, 0x8a, 0x80, 0x75, 0x4e, 0xae, 0x10, 0x47, 0x0e, 0x28,
		0x32, 0x8b, 0x31, 0xf8, 0x7f, 0x1f, 0x64, 0xc9, 0xaa, 0xa8, 0x2f, 0x1e, 0x29, 0x39, 0x96, 0xdd,
		0x7b, 0x08, 0x10, 0x4b, 0x14, 0xc5, 0xfb, 0xe4, 0xef, 0x8e, 0x77, 0xf6, 0x7f, 0x03, 0xc7, 0x71,
		0x1c, 0xf7, 0x4f, 0xf6, 0x08, 0xee, 0xd4, 0x71, 0xef, 0xe1, 0x39, 0x98, 0x81, 0x7b, 0x92, 0x5c,
		0xfd, 0x18, 0x84, 0xf7, 0xee, 0xd4, 0xf1, 0xd2, 0x8f, 0xef, 0x96, 0xa1, 0x1f, 0xcc, 0xdd, 0xa9,
		0x33, 0x4a, 0x2f, 0x5c, 0x05, 0xdc, 0x9d, 0x3a, 0xc9, 0x14, 0x9b, 0x0b, 0x4b, 0x7e, 0x0f, 0x1c,
		0xee, 0xdf, 0x2c, 0x82, 0x48, 0x44, 0xca, 0x2d, 0xe5, 0x2d, 0xea, 0xb0, 0x13, 0x75, 0x90, 0xfa,
		0xd2, 0xec, 0x72, 0xf1, 0xe5, 0xd9, 0x8d, 0x4f, 0x1c, 0xfc, 0xe0, 0xa5, 0xf4, 0x32, 0xe5, 0x85,
		0xb3, 0xd2, 0x6b, 0x36, 0xb7, 0x3f, 0x2f, 0x25, 0x9f, 0x41, 0xe5, 0xa3, 0xc9, 0x52, 0x60, 0xf5,
		0xef, 0x92, 0xc7, 0xab, 0x71, 0x9f, 0x92, 0xb7, 0x9c, 0x54, 0x0f, 0xfc, 0x9d, 0x45, 0x97, 0x7c,
		0x2e, 0x1f, 0x21, 0x14, 0xee, 0xd4, 0x11, 0x5c, 0x42, 0xcd, 0xc0, 0xdc, 0xa8, 0xcd, 0xa2, 0x4a,
		0xa3, 0xd6, 0xca, 0x95, 0x75, 0x81, 0xd6, 0x22, 0xc3, 0x2b, 0x19, 0x5f, 0x4f, 0x4f, 0x15, 0xff,
		0xeb, 0x48, 0xaa, 0x16, 0x83, 0x56, 0x1c, 0x18, 0xb1, 0x20, 0xc5, 0x83, 0x15, 0x93, 0xb1, 0xb8,
		0x8c, 0xc5, 0x86, 0x17, 0x5f, 0xb5, 0x18, 0x6b, 0xc4, 0xa9, 0x15, 0x6b, 0x36, 0x60, 0xb6, 0xe5,
		0xb6, 0x86, 0x03, 0x19, 0x43, 0x93, 0xf1, 0x1a, 0x6a, 0x9a, 0x45, 0x8c, 0x16, 0xb5, 0x89, 0xc8,
		0x0d, 0x45, 0x6f, 0xaa, 0x02, 0xd6, 0xaa, 0x60, 0xad, 0x12, 0xe6, 0xaa, 0xd1, 0xac, 0x22, 0x1a,
		0x55, 0x41, 0xab, 0x4c, 0x36, 0xf0, 0x01, 0x56, 0x78, 0xb6, 0x6d, 0xa5, 0x12, 0x3f, 0x84, 0xa4,
		0x3b, 0x55, 0xa2, 0x11, 0x72, 0x38, 0x56, 0x99, 0x6c, 0x94, 0xca, 0x52, 0xb9, 0x6c, 0x95, 0xac,
		0xb5, 0xb2, 0xb5, 0x56, 0x3a, 0x7b, 0xe5, 0xc3, 0x29, 0x21, 0x52, 0x19, 0xb3, 0x65, 0x7c, 0x59,
		0x3d, 0x81, 0x9d, 0xa4, 0x22, 0xc1, 0x83, 0x70, 0x6e, 0x22, 0xac, 0xad, 0xf3, 0xba, 0x18, 0x74,
		0x43, 0x27, 0x82, 0x46, 0xf7, 0x99, 0x2d, 0x24, 0x98, 0x5b, 0x53, 0xf2, 0x18, 0xd9, 0x13, 0xd9,
		0xd3, 0xcf, 0x64, 0x4f, 0xad, 0xb6, 0xb7, 0xcb, 0x30, 0x5c, 0x0a, 0x26, 0x82, 0x65, 0x88, 0xdb,
		0xe5, 0xa2, 0xd9, 0x77, 0x78, 0x64, 0x4f, 0x4c, 0x7c, 0x8f, 0xa9, 0x1f, 0xce, 0x04, 0x44, 0x22,
		0xb9, 0x36, 0x54, 0x82, 0x0d, 0xe5, 0xd3, 0x10, 0x05, 0x93, 0x92, 0xf9, 0x05, 0x97, 0x33, 0x11,
		0xa6, 0xdc, 0x7d, 0xf7, 0x63, 0xfa, 0xbb, 0xbf, 0x92, 0x09, 0xff, 0x88, 0x67, 0xcf, 0x7f, 0xb8,
		0x4b, 0x2d, 0x73, 0x60, 0xc7, 0xa4, 0x06, 0x06, 0xa1, 0xb6, 0x74, 0x83, 0xad, 0x1c, 0xe9, 0x72,
		0x08, 0x07, 0xf6, 0x11, 0x07, 0xa2, 0x5d, 0x44, 0xc6, 0xe9, 0x05, 0x30, 0x9f, 0x83, 0x8f, 0xe1,
		0xf6, 0xd6, 0x27, 0x9c, 0x23, 0xc6, 0x7e, 0x4a, 0x6d, 0xef, 0xed, 0xdb, 0xd4, 0xac, 0x86, 0xb1,
		0xe6, 0xed, 0x40, 0xfb, 0x23, 0xc1, 0x04, 0xe0, 0xf5, 0x3f, 0x19, 0xde, 0x71, 0x24, 0x34, 0x26,
		0x0b, 0xa0, 0x48, 0x88, 0x90, 0x1b, 0x21, 0x37, 0x8a, 0x84, 0x28, 0x12, 0x22, 0x7b, 0x22, 0x7b,
		0x3a, 0xf4, 0x48, 0x08, 0x83, 0x92, 0x6c, 0x03, 0xa1, 0xcf, 0x9b, 0xb9, 0x6d, 0x91, 0xa0, 0x51,
		0x22, 0xfd, 0xe3, 0x66, 0x8b, 0x6f, 0xd8, 0xb4, 0xdd, 0x78, 0x45, 0x97, 0x42, 0x68, 0xf2, 0xed,
		0xd7, 0x41, 0xf8, 0x7e, 0x01, 0xb1, 0xde, 0x47, 0xcd, 0x0e, 0xc5, 0xbd, 0x66, 0x2f, 0xb9, 0x91,
		0xde, 0xc5, 0x64, 0x72, 0x76, 0x3e, 0x99, 0x8c, 0xce, 0x7f, 0x39, 0x1f, 0xfd, 0x7a, 0x7a, 0xea,
		0x9d, 0x79, 0xa7, 0x0d, 0x0f, 0xa7, 0x5c, 0xfa, 0xcd, 0x20, 0x9c, 0x93, 0x11, 0x70, 0x1d, 0x9a,
		0x35, 0xf0, 0x36, 0x79, 0x0f, 0xb3, 0x55, 0x88, 0x6f, 0x18, 0xc4, 0x63, 0xe5, 0x59, 0x14, 0x6f,
		0xb2, 0xa1, 0x64, 0x07, 0xf1, 0x41, 0xc6, 0xd4, 0xdb, 0xf8, 0x05, 0xc9, 0xd2, 0x8c, 0x94, 0x08,
		0x5e, 0x04, 0x67, 0x6f, 0x64, 0x18, 0x09, 0xf6, 0x6d, 0xd1, 0xcc, 0xc6, 0x3c, 0xcf, 0xa6, 0xce,
		0x3f, 0x8d, 0xd4, 0x18, 0x84, 0x02, 0x08, 0x21, 0xb7, 0x8d, 0x05, 0x8c, 0x84, 0xdd, 0x5d, 0x3c,
		0xa0, 0x17, 0x3a, 0xc2, 0x63, 0xd6, 0xde, 0xfd, 0x6a, 0x24, 0x67, 0xa4, 0x67, 0xb5, 0xf3, 0xa8,
		0x6e, 0x63, 0x04, 0x6b, 0xea, 0x43, 0xab, 0x59, 0xb6, 0x36, 0x3c, 0x3d, 0xd6, 0x10, 0x8c, 0x26,
		0xb4, 0xea, 0x28, 0x1d, 0x47, 0x93, 0x4a, 0xc7, 0x8f, 0xd5, 0xe6, 0x56, 0x9a, 0x69, 0xe6, 0xa3,
		0x5c, 0x88, 0xe0, 0x01, 0x56, 0xf8, 0x72, 0x82, 0xd2, 0x13, 0x54, 0x59, 0x80, 0xd6, 0x0d, 0x6d,
		0x65, 0x41, 0x81, 0xb9, 0xf8, 0x22, 0x83, 0xe2, 0x83, 0x54, 0x6f, 0x40, 0xf5, 0x06, 0x94, 0x67,
		0x3e, 0xe6, 0x2c, 0x9b, 0x67, 0x95, 0x66, 0xf3, 0x28, 0x2f, 0x40, 0x79, 0x01, 0xca, 0xb3, 0x95,
		0xac, 0x69, 0x6c, 0x65, 0x4d, 0x63, 0xb2, 0x26, 0xb2, 0xa6, 0xd7, 0xb3, 0x26, 0x19, 0x84, 0xe2,
		0x6c, 0x62, 0x61, 0x4d, 0x17, 0x06, 0x8f, 0xdc, 0xb0, 0x70, 0x0e, 0xda, 0x38, 0xdb, 0x3c, 0xee,
		0xae, 0x4a, 0xff, 0x18, 0x6b, 0x51, 0xf6, 0xf0, 0xdf, 0x69, 0x6a, 0x7c, 0x74, 0x62, 0xf7, 0xfc,
		0x07, 0xce, 0x66, 0x71, 0x8c, 0x76, 0x15, 0xcc, 0x03, 0x5d, 0xfa, 0xa9, 0x59, 0x36, 0x30, 0x67,
		0x22, 0x78, 0x8e, 0xd7, 0xe2, 0xb3, 0x45, 0x04, 0xc6, 0xb3, 0xac, 0x4f, 0x2c, 0x58, 0xc7, 0x5e,
		0xda, 0xb3, 0xce, 0x2c, 0x8d, 0x76, 0x28, 0xdc, 0x1c, 0xec, 0x66, 0xf4, 0x57, 0x3a, 0xf6, 0xa1,
		0x0d, 0x89, 0x36, 0xa4, 0xfe, 0xc1, 0xbb, 0xbe, 0x1d, 0xfb, 0x14, 0xd3, 0x63, 0x75, 0x37, 0xba,
		0x2c, 0x8b, 0xbb, 0xce, 0xa6, 0x56, 0x72, 0x9a, 0xea, 0xe5, 0xdd, 0x96, 0xca, 0x79, 0x46, 0xb5,
		0x72, 0x1e, 0x15, 0xcb, 0x51, 0xb1, 0xdc, 0x7e, 0x8a, 0xe5, 0xbc, 0x1d, 0x19, 0xc0, 0xd8, 0xc8,
		0x00, 0xc6, 0x64, 0x00, 0x64, 0x00, 0xfb, 0x31, 0x80, 0x31, 0x95, 0x8b, 0x92, 0x09, 0x50, 0x22,
		0x9b, 0x22, 0x1d, 0x8a, 0x74, 0x28, 0x91, 0x4d, 0x89, 0x6c, 0xb2, 0x26, 0x4a, 0x64, 0x53, 0x22,
		0x9b, 0x12, 0xd9, 0x94, 0xc8, 0xa6, 0x44, 0x36, 0x6d, 0x48, 0x04, 0xef, 0x28, 0x91, 0x6d, 0x9a,
		0xc8, 0xee, 0xae, 0xab, 0x01, 0x97, 0xc7, 0xde, 0x4b, 0xa7, 0x83, 0xe7, 0x34, 0xa0, 0x64, 0xea,
		0x77, 0xa8, 0xf7, 0x48, 0xd4, 0xef, 0x90, 0x4c, 0x40, 0xfd, 0x0e, 0xbb, 0x4b, 0x68, 0x1d, 0x69,
		0xbf, 0x03, 0xd6, 0x03, 0xb7, 0xea, 0x82, 0x40, 0xf9, 0xdc, 0xde, 0x74, 0x46, 0x68, 0x9a, 0x0f,
		0xac, 0x48, 0xc6, 0xb4, 0x4b, 0x70, 0xf0, 0xeb, 0x3b, 0x23, 0xca, 0x99, 0xfb, 0x9d, 0x34, 0x41,
		0xf0, 0x1e, 0xf6, 0x40, 0xf0, 0xee, 0x5a, 0x20, 0x38, 0xf8, 0xc0, 0x21, 0x6c, 0xa2, 0x25, 0xc7,
		0xf0, 0x74, 0x68, 0x0f, 0xda, 0x1c, 0xf8, 0x01, 0x76, 0x39, 0xf0, 0xd7, 0x6b, 0x72, 0x48, 0xed,
		0x10, 0x09, 0x44, 0x36, 0xa3, 0x0f, 0xe0, 0x68, 0x94, 0x1f, 0xe1, 0xb1, 0x10, 0xff, 0xf9, 0x0e,
		0x46, 0x87, 0x22, 0x9a, 0x0a, 0xc6, 0xe7, 0x20, 0xe2, 0xff, 0x20, 0x14, 0x81, 0x58, 0xc5, 0xff,
		0x6d, 0xd4, 0xf0, 0x35, 0x23, 0x8c, 0x06, 0xbd, 0xef, 0x6f, 0x70, 0x11, 0xca, 0xc5, 0xc2, 0x00,
		0x32, 0xd7, 0xe7, 0xc1, 0x3a, 0xc6, 0x52, 0x1c, 0xfc, 0x14, 0x36, 0x70, 0xf0, 0x87, 0xba, 0xcd,
		0xa2, 0x02, 0x33, 0xdc, 0x6c, 0x27, 0xb8, 0xbb, 0x01, 0x3f, 0xfe, 0x4b, 0x27, 0xd8, 0x07, 0x0a,
		0x52, 0x88, 0xd1, 0xc3, 0x1d, 0x65, 0xe9, 0x18, 0x64, 0x93, 0xa8, 0x7f, 0x3d, 0xb8, 0x49, 0xef,
		0xbf, 0x02, 0xbe, 0x91, 0x7d, 0x6c, 0xf2, 0x94, 0x1d, 0x36, 0x79, 0x26, 0xfe, 0x45, 0x0f, 0x6f,
		0xd2, 0x71, 0x3d, 0xc0, 0x36, 0xf2, 0x10, 0x5b, 0x38, 0xa5, 0x20, 0x74, 0xd3, 0x0e, 0xdd, 0xc8,
		0x63, 0xac, 0x7a, 0x91, 0x7d, 0x2c, 0xfc, 0x42, 0xe7, 0x9d, 0x91, 0xf9, 0x66, 0x82, 0x25, 0xfd,
		0x85, 0x25, 0x32, 0x97, 0xcf, 0x48, 0x41, 0x67, 0xa3, 0xa7, 0xaf, 0xd8, 0xdd, 0x6f, 0x73, 0xc9,
		0x8c, 0x2f, 0x9b, 0x29, 0xee, 0xde, 0x27, 0x53, 0xec, 0x03, 0x9a, 0x94, 0x09, 0xd2, 0xe3, 0x93,
		0x32, 0x05, 0x18, 0x90, 0x22, 0x43, 0xe4, 0x6f, 0x5e, 0x14, 0x07, 0xd2, 0x77, 0x53, 0xb4, 0x87,
		0x2d, 0x2a, 0x4f, 0xf5, 0xf0, 0xa5, 0x30, 0x9e, 0xbe, 0x89, 0x82, 0xbe, 0x89, 0x62, 0x7f, 0x50,
		0x86, 0x0a, 0x78, 0xed, 0xa0, 0x0c, 0x7d, 0xdf, 0x6b, 0x67, 0xca, 0x65, 0xab, 0x64, 0xad, 0x95,
		0xad, 0xb5, 0xd2, 0xd9, 0x2b, 0x1f, 0x4e, 0x09, 0x91, 0xca, 0x68, 0x8e, 0xaf, 0xed, 0x71, 0xb6,
		0x21, 0xde, 0xc6, 0xd3, 0x49, 0xf5, 0x52, 0x64, 0x4f, 0x64, 0x4f, 0x47, 0x58, 0x2f, 0x55, 0x08,
		0x39, 0x0a, 0x9f, 0x3b, 0x69, 0xf3, 0xbd, 0xdd, 0x4e, 0x99, 0x1c, 0xd1, 0x2b, 0x1f, 0xe9, 0x17,
		0x30, 0x08, 0x0f, 0xd2, 0x2f, 0x60, 0x50, 0x4b, 0x23, 0x59, 0x00, 0x45, 0x44, 0x84, 0xe0, 0x08,
		0xc1, 0x51, 0x44, 0x44, 0x11, 0x11, 0xd9, 0x13, 0x45, 0x44, 0xfd, 0x8d, 0x88, 0x3a, 0xe8, 0x17,
		0x69, 0x0c, 0x88, 0xe8, 0x97, 0x30, 0xea, 0x1e, 0x3e, 0x84, 0x53, 0x52, 0xbc, 0x22, 0xd9, 0x95,
		0xbd, 0x37, 0xa9, 0xce, 0xde, 0xcb, 0xdc, 0x9b, 0x8f, 0x2f, 0x8d, 0x28, 0xab, 0x3d, 0x56, 0x1d,
		0xe4, 0xd6, 0x5c, 0xb7, 0x56, 0x37, 0x88, 0x3e, 0xb0, 0x07, 0xb8, 0x59, 0x2e, 0xcb, 0xee, 0xbc,
		0xb8, 0x7e, 0x37, 0x7f, 0x4b, 0x59, 0xdc, 0x15, 0x3c, 0x07, 0xdb, 0xaa, 0xb9, 0xf5, 0x60, 0xfd,
		0x3f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xcb, 0xf9, 0x00, 0x05,
		0x81, 0x00, 0x00,
	}
)

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
func initΛEnumTypes() {
	ΛEnumTypes = map[string][]reflect.Type{}
}
