/*
Package exampleoc is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

NOTE WELL: This is an example code file that is distributed with ygot.
It should not be used within your application, as it WILL change,
without warning. Rather, you should generate structs directly from
OpenConfig models using the ygot package.

This package was generated by github.com/openconfig/ygot
using the following YANG input files:
	- public/release/models/network-instance/openconfig-network-instance.yang
	- public/release/models/optical-transport/openconfig-optical-amplifier.yang
	- public/release/models/optical-transport/openconfig-terminal-device.yang
	- public/release/models/optical-transport/openconfig-transport-line-protection.yang
	- public/release/models/platform/openconfig-platform.yang
	- public/release/models/policy/openconfig-routing-policy.yang
	- public/release/models/lacp/openconfig-lacp.yang
	- public/release/models/system/openconfig-system.yang
	- public/release/models/lldp/openconfig-lldp.yang
	- public/release/models/stp/openconfig-spanning-tree.yang
	- public/release/models/interfaces/openconfig-interfaces.yang
	- public/release/models/interfaces/openconfig-if-ip.yang
	- public/release/models/interfaces/openconfig-if-aggregate.yang
	- public/release/models/interfaces/openconfig-if-ethernet.yang
	- public/release/models/interfaces/openconfig-if-ip-ext.yang
Imported modules were sourced from:
	- public/...
	- deps/...
*/
package exampleoc

import (
	"github.com/openconfig/ygot/ygot"
)

// Stp represents the /openconfig-spanning-tree/stp YANG schema element.
type Stp struct {
	ΛMetadata  []ygot.Annotation         `path:"@" ygotAnnotation:"true"`
	Global     *Stp_Global               `path:"global" module:"openconfig-spanning-tree"`
	ΛGlobal    []ygot.Annotation         `path:"@global" ygotAnnotation:"true"`
	Interface  map[string]*Stp_Interface `path:"interfaces/interface" module:"openconfig-spanning-tree"`
	ΛInterface []ygot.Annotation         `path:"interfaces/@interface" ygotAnnotation:"true"`
	Mstp       *Stp_Mstp                 `path:"mstp" module:"openconfig-spanning-tree"`
	ΛMstp      []ygot.Annotation         `path:"@mstp" ygotAnnotation:"true"`
	Rstp       *Stp_Rstp                 `path:"rstp" module:"openconfig-spanning-tree"`
	ΛRstp      []ygot.Annotation         `path:"@rstp" ygotAnnotation:"true"`
	Vlan       map[uint16]*Stp_Vlan      `path:"rapid-pvst/vlan" module:"openconfig-spanning-tree"`
	ΛVlan      []ygot.Annotation         `path:"rapid-pvst/@vlan" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp) IsYANGGoStruct() {}

// Stp_Global represents the /openconfig-spanning-tree/stp/global YANG schema element.
type Stp_Global struct {
	ΛMetadata                   []ygot.Annotation                            `path:"@" ygotAnnotation:"true"`
	BpduFilter                  *bool                                        `path:"config/bpdu-filter" module:"openconfig-spanning-tree"`
	ΛBpduFilter                 []ygot.Annotation                            `path:"config/@bpdu-filter" ygotAnnotation:"true"`
	BpduGuard                   *bool                                        `path:"config/bpdu-guard" module:"openconfig-spanning-tree"`
	ΛBpduGuard                  []ygot.Annotation                            `path:"config/@bpdu-guard" ygotAnnotation:"true"`
	BpduguardTimeoutRecovery    *uint8                                       `path:"config/bpduguard-timeout-recovery" module:"openconfig-spanning-tree"`
	ΛBpduguardTimeoutRecovery   []ygot.Annotation                            `path:"config/@bpduguard-timeout-recovery" ygotAnnotation:"true"`
	BridgeAssurance             *bool                                        `path:"config/bridge-assurance" module:"openconfig-spanning-tree"`
	ΛBridgeAssurance            []ygot.Annotation                            `path:"config/@bridge-assurance" ygotAnnotation:"true"`
	EnabledProtocol             []E_OpenconfigSpanningTreeTypes_STP_PROTOCOL `path:"config/enabled-protocol" module:"openconfig-spanning-tree"`
	ΛEnabledProtocol            []ygot.Annotation                            `path:"config/@enabled-protocol" ygotAnnotation:"true"`
	EtherchannelMisconfigGuard  *bool                                        `path:"config/etherchannel-misconfig-guard" module:"openconfig-spanning-tree"`
	ΛEtherchannelMisconfigGuard []ygot.Annotation                            `path:"config/@etherchannel-misconfig-guard" ygotAnnotation:"true"`
	LoopGuard                   *bool                                        `path:"config/loop-guard" module:"openconfig-spanning-tree"`
	ΛLoopGuard                  []ygot.Annotation                            `path:"config/@loop-guard" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Global implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Global) IsYANGGoStruct() {}

// Stp_Interface represents the /openconfig-spanning-tree/stp/interfaces/interface YANG schema element.
type Stp_Interface struct {
	ΛMetadata   []ygot.Annotation                           `path:"@" ygotAnnotation:"true"`
	BpduFilter  *bool                                       `path:"config/bpdu-filter" module:"openconfig-spanning-tree"`
	ΛBpduFilter []ygot.Annotation                           `path:"config/@bpdu-filter" ygotAnnotation:"true"`
	BpduGuard   *bool                                       `path:"config/bpdu-guard" module:"openconfig-spanning-tree"`
	ΛBpduGuard  []ygot.Annotation                           `path:"config/@bpdu-guard" ygotAnnotation:"true"`
	EdgePort    E_OpenconfigSpanningTreeTypes_STP_EDGE_PORT `path:"config/edge-port" module:"openconfig-spanning-tree"`
	ΛEdgePort   []ygot.Annotation                           `path:"config/@edge-port" ygotAnnotation:"true"`
	Guard       E_OpenconfigSpanningTree_StpGuardType       `path:"config/guard" module:"openconfig-spanning-tree"`
	ΛGuard      []ygot.Annotation                           `path:"config/@guard" ygotAnnotation:"true"`
	LinkType    E_OpenconfigSpanningTree_StpLinkType        `path:"config/link-type" module:"openconfig-spanning-tree"`
	ΛLinkType   []ygot.Annotation                           `path:"config/@link-type" ygotAnnotation:"true"`
	Name        *string                                     `path:"config/name|name" module:"openconfig-spanning-tree"`
	ΛName       []ygot.Annotation                           `path:"config/@name|@name" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Interface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Interface) IsYANGGoStruct() {}

// Stp_Mstp represents the /openconfig-spanning-tree/stp/mstp YANG schema element.
type Stp_Mstp struct {
	ΛMetadata        []ygot.Annotation                `path:"@" ygotAnnotation:"true"`
	ForwardingDelay  *uint8                           `path:"config/forwarding-delay" module:"openconfig-spanning-tree"`
	ΛForwardingDelay []ygot.Annotation                `path:"config/@forwarding-delay" ygotAnnotation:"true"`
	HelloTime        *uint8                           `path:"config/hello-time" module:"openconfig-spanning-tree"`
	ΛHelloTime       []ygot.Annotation                `path:"config/@hello-time" ygotAnnotation:"true"`
	HoldCount        *uint8                           `path:"config/hold-count" module:"openconfig-spanning-tree"`
	ΛHoldCount       []ygot.Annotation                `path:"config/@hold-count" ygotAnnotation:"true"`
	MaxAge           *uint8                           `path:"config/max-age" module:"openconfig-spanning-tree"`
	ΛMaxAge          []ygot.Annotation                `path:"config/@max-age" ygotAnnotation:"true"`
	MaxHop           *uint8                           `path:"config/max-hop" module:"openconfig-spanning-tree"`
	ΛMaxHop          []ygot.Annotation                `path:"config/@max-hop" ygotAnnotation:"true"`
	MstInstance      map[uint16]*Stp_Mstp_MstInstance `path:"mst-instances/mst-instance" module:"openconfig-spanning-tree"`
	ΛMstInstance     []ygot.Annotation                `path:"mst-instances/@mst-instance" ygotAnnotation:"true"`
	Name             *string                          `path:"config/name" module:"openconfig-spanning-tree"`
	ΛName            []ygot.Annotation                `path:"config/@name" ygotAnnotation:"true"`
	Revision         *uint32                          `path:"config/revision" module:"openconfig-spanning-tree"`
	ΛRevision        []ygot.Annotation                `path:"config/@revision" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Mstp implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Mstp) IsYANGGoStruct() {}

// Stp_Mstp_MstInstance represents the /openconfig-spanning-tree/stp/mstp/mst-instances/mst-instance YANG schema element.
type Stp_Mstp_MstInstance struct {
	ΛMetadata                []ygot.Annotation                          `path:"@" ygotAnnotation:"true"`
	BridgeAddress            *string                                    `path:"state/bridge-address" module:"openconfig-spanning-tree"`
	ΛBridgeAddress           []ygot.Annotation                          `path:"state/@bridge-address" ygotAnnotation:"true"`
	BridgePriority           *uint32                                    `path:"config/bridge-priority" module:"openconfig-spanning-tree"`
	ΛBridgePriority          []ygot.Annotation                          `path:"config/@bridge-priority" ygotAnnotation:"true"`
	DesignatedRootAddress    *string                                    `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress   []ygot.Annotation                          `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority   *uint32                                    `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority  []ygot.Annotation                          `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	HoldTime                 *uint8                                     `path:"state/hold-time" module:"openconfig-spanning-tree"`
	ΛHoldTime                []ygot.Annotation                          `path:"state/@hold-time" ygotAnnotation:"true"`
	Interface                map[string]*Stp_Mstp_MstInstance_Interface `path:"interfaces/interface" module:"openconfig-spanning-tree"`
	ΛInterface               []ygot.Annotation                          `path:"interfaces/@interface" ygotAnnotation:"true"`
	MstId                    *uint16                                    `path:"config/mst-id|mst-id" module:"openconfig-spanning-tree"`
	ΛMstId                   []ygot.Annotation                          `path:"config/@mst-id|@mst-id" ygotAnnotation:"true"`
	RootCost                 *uint32                                    `path:"state/root-cost" module:"openconfig-spanning-tree"`
	ΛRootCost                []ygot.Annotation                          `path:"state/@root-cost" ygotAnnotation:"true"`
	RootPort                 *uint16                                    `path:"state/root-port" module:"openconfig-spanning-tree"`
	ΛRootPort                []ygot.Annotation                          `path:"state/@root-port" ygotAnnotation:"true"`
	TimeSinceTopologyChange  *uint64                                    `path:"state/time-since-topology-change" module:"openconfig-spanning-tree"`
	ΛTimeSinceTopologyChange []ygot.Annotation                          `path:"state/@time-since-topology-change" ygotAnnotation:"true"`
	TopologyChanges          *uint64                                    `path:"state/topology-changes" module:"openconfig-spanning-tree"`
	ΛTopologyChanges         []ygot.Annotation                          `path:"state/@topology-changes" ygotAnnotation:"true"`
	Vlan                     []Stp_Mstp_MstInstance_Vlan_Union          `path:"config/vlan" module:"openconfig-spanning-tree"`
	ΛVlan                    []ygot.Annotation                          `path:"config/@vlan" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Mstp_MstInstance implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Mstp_MstInstance) IsYANGGoStruct() {}

// Stp_Mstp_MstInstance_Interface represents the /openconfig-spanning-tree/stp/mstp/mst-instances/mst-instance/interfaces/interface YANG schema element.
type Stp_Mstp_MstInstance_Interface struct {
	ΛMetadata                 []ygot.Annotation                            `path:"@" ygotAnnotation:"true"`
	Cost                      *uint32                                      `path:"config/cost" module:"openconfig-spanning-tree"`
	ΛCost                     []ygot.Annotation                            `path:"config/@cost" ygotAnnotation:"true"`
	Counters                  *Stp_Mstp_MstInstance_Interface_Counters     `path:"state/counters" module:"openconfig-spanning-tree"`
	ΛCounters                 []ygot.Annotation                            `path:"state/@counters" ygotAnnotation:"true"`
	DesignatedBridgeAddress   *string                                      `path:"state/designated-bridge-address" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgeAddress  []ygot.Annotation                            `path:"state/@designated-bridge-address" ygotAnnotation:"true"`
	DesignatedBridgePriority  *uint32                                      `path:"state/designated-bridge-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgePriority []ygot.Annotation                            `path:"state/@designated-bridge-priority" ygotAnnotation:"true"`
	DesignatedCost            *uint32                                      `path:"state/designated-cost" module:"openconfig-spanning-tree"`
	ΛDesignatedCost           []ygot.Annotation                            `path:"state/@designated-cost" ygotAnnotation:"true"`
	DesignatedPortNum         *uint16                                      `path:"state/designated-port-num" module:"openconfig-spanning-tree"`
	ΛDesignatedPortNum        []ygot.Annotation                            `path:"state/@designated-port-num" ygotAnnotation:"true"`
	DesignatedPortPriority    *uint8                                       `path:"state/designated-port-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedPortPriority   []ygot.Annotation                            `path:"state/@designated-port-priority" ygotAnnotation:"true"`
	DesignatedRootAddress     *string                                      `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress    []ygot.Annotation                            `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority    *uint32                                      `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority   []ygot.Annotation                            `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	ForwardTransisitions      *uint64                                      `path:"state/forward-transisitions" module:"openconfig-spanning-tree"`
	ΛForwardTransisitions     []ygot.Annotation                            `path:"state/@forward-transisitions" ygotAnnotation:"true"`
	Name                      *string                                      `path:"config/name|name" module:"openconfig-spanning-tree"`
	ΛName                     []ygot.Annotation                            `path:"config/@name|@name" ygotAnnotation:"true"`
	PortNum                   *uint16                                      `path:"state/port-num" module:"openconfig-spanning-tree"`
	ΛPortNum                  []ygot.Annotation                            `path:"state/@port-num" ygotAnnotation:"true"`
	PortPriority              *uint8                                       `path:"config/port-priority" module:"openconfig-spanning-tree"`
	ΛPortPriority             []ygot.Annotation                            `path:"config/@port-priority" ygotAnnotation:"true"`
	PortState                 E_OpenconfigSpanningTreeTypes_STP_PORT_STATE `path:"state/port-state" module:"openconfig-spanning-tree"`
	ΛPortState                []ygot.Annotation                            `path:"state/@port-state" ygotAnnotation:"true"`
	Role                      E_OpenconfigSpanningTreeTypes_STP_PORT_ROLE  `path:"state/role" module:"openconfig-spanning-tree"`
	ΛRole                     []ygot.Annotation                            `path:"state/@role" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Mstp_MstInstance_Interface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Mstp_MstInstance_Interface) IsYANGGoStruct() {}

// Stp_Mstp_MstInstance_Interface_Counters represents the /openconfig-spanning-tree/stp/mstp/mst-instances/mst-instance/interfaces/interface/state/counters YANG schema element.
type Stp_Mstp_MstInstance_Interface_Counters struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	BpduReceived  *uint64           `path:"bpdu-received" module:"openconfig-spanning-tree"`
	ΛBpduReceived []ygot.Annotation `path:"@bpdu-received" ygotAnnotation:"true"`
	BpduSent      *uint64           `path:"bpdu-sent" module:"openconfig-spanning-tree"`
	ΛBpduSent     []ygot.Annotation `path:"@bpdu-sent" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Mstp_MstInstance_Interface_Counters implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Mstp_MstInstance_Interface_Counters) IsYANGGoStruct() {}

// Stp_Rstp represents the /openconfig-spanning-tree/stp/rstp YANG schema element.
type Stp_Rstp struct {
	ΛMetadata                []ygot.Annotation              `path:"@" ygotAnnotation:"true"`
	BridgeAddress            *string                        `path:"state/bridge-address" module:"openconfig-spanning-tree"`
	ΛBridgeAddress           []ygot.Annotation              `path:"state/@bridge-address" ygotAnnotation:"true"`
	BridgePriority           *uint32                        `path:"config/bridge-priority" module:"openconfig-spanning-tree"`
	ΛBridgePriority          []ygot.Annotation              `path:"config/@bridge-priority" ygotAnnotation:"true"`
	DesignatedRootAddress    *string                        `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress   []ygot.Annotation              `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority   *uint32                        `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority  []ygot.Annotation              `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	ForwardingDelay          *uint8                         `path:"config/forwarding-delay" module:"openconfig-spanning-tree"`
	ΛForwardingDelay         []ygot.Annotation              `path:"config/@forwarding-delay" ygotAnnotation:"true"`
	HelloTime                *uint8                         `path:"config/hello-time" module:"openconfig-spanning-tree"`
	ΛHelloTime               []ygot.Annotation              `path:"config/@hello-time" ygotAnnotation:"true"`
	HoldCount                *uint8                         `path:"config/hold-count" module:"openconfig-spanning-tree"`
	ΛHoldCount               []ygot.Annotation              `path:"config/@hold-count" ygotAnnotation:"true"`
	HoldTime                 *uint8                         `path:"state/hold-time" module:"openconfig-spanning-tree"`
	ΛHoldTime                []ygot.Annotation              `path:"state/@hold-time" ygotAnnotation:"true"`
	Interface                map[string]*Stp_Rstp_Interface `path:"interfaces/interface" module:"openconfig-spanning-tree"`
	ΛInterface               []ygot.Annotation              `path:"interfaces/@interface" ygotAnnotation:"true"`
	MaxAge                   *uint8                         `path:"config/max-age" module:"openconfig-spanning-tree"`
	ΛMaxAge                  []ygot.Annotation              `path:"config/@max-age" ygotAnnotation:"true"`
	RootCost                 *uint32                        `path:"state/root-cost" module:"openconfig-spanning-tree"`
	ΛRootCost                []ygot.Annotation              `path:"state/@root-cost" ygotAnnotation:"true"`
	RootPort                 *uint16                        `path:"state/root-port" module:"openconfig-spanning-tree"`
	ΛRootPort                []ygot.Annotation              `path:"state/@root-port" ygotAnnotation:"true"`
	TimeSinceTopologyChange  *uint64                        `path:"state/time-since-topology-change" module:"openconfig-spanning-tree"`
	ΛTimeSinceTopologyChange []ygot.Annotation              `path:"state/@time-since-topology-change" ygotAnnotation:"true"`
	TopologyChanges          *uint64                        `path:"state/topology-changes" module:"openconfig-spanning-tree"`
	ΛTopologyChanges         []ygot.Annotation              `path:"state/@topology-changes" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Rstp implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Rstp) IsYANGGoStruct() {}

// Stp_Rstp_Interface represents the /openconfig-spanning-tree/stp/rstp/interfaces/interface YANG schema element.
type Stp_Rstp_Interface struct {
	ΛMetadata                 []ygot.Annotation                            `path:"@" ygotAnnotation:"true"`
	Cost                      *uint32                                      `path:"config/cost" module:"openconfig-spanning-tree"`
	ΛCost                     []ygot.Annotation                            `path:"config/@cost" ygotAnnotation:"true"`
	Counters                  *Stp_Rstp_Interface_Counters                 `path:"state/counters" module:"openconfig-spanning-tree"`
	ΛCounters                 []ygot.Annotation                            `path:"state/@counters" ygotAnnotation:"true"`
	DesignatedBridgeAddress   *string                                      `path:"state/designated-bridge-address" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgeAddress  []ygot.Annotation                            `path:"state/@designated-bridge-address" ygotAnnotation:"true"`
	DesignatedBridgePriority  *uint32                                      `path:"state/designated-bridge-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgePriority []ygot.Annotation                            `path:"state/@designated-bridge-priority" ygotAnnotation:"true"`
	DesignatedCost            *uint32                                      `path:"state/designated-cost" module:"openconfig-spanning-tree"`
	ΛDesignatedCost           []ygot.Annotation                            `path:"state/@designated-cost" ygotAnnotation:"true"`
	DesignatedPortNum         *uint16                                      `path:"state/designated-port-num" module:"openconfig-spanning-tree"`
	ΛDesignatedPortNum        []ygot.Annotation                            `path:"state/@designated-port-num" ygotAnnotation:"true"`
	DesignatedPortPriority    *uint8                                       `path:"state/designated-port-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedPortPriority   []ygot.Annotation                            `path:"state/@designated-port-priority" ygotAnnotation:"true"`
	DesignatedRootAddress     *string                                      `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress    []ygot.Annotation                            `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority    *uint32                                      `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority   []ygot.Annotation                            `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	ForwardTransisitions      *uint64                                      `path:"state/forward-transisitions" module:"openconfig-spanning-tree"`
	ΛForwardTransisitions     []ygot.Annotation                            `path:"state/@forward-transisitions" ygotAnnotation:"true"`
	Name                      *string                                      `path:"config/name|name" module:"openconfig-spanning-tree"`
	ΛName                     []ygot.Annotation                            `path:"config/@name|@name" ygotAnnotation:"true"`
	PortNum                   *uint16                                      `path:"state/port-num" module:"openconfig-spanning-tree"`
	ΛPortNum                  []ygot.Annotation                            `path:"state/@port-num" ygotAnnotation:"true"`
	PortPriority              *uint8                                       `path:"config/port-priority" module:"openconfig-spanning-tree"`
	ΛPortPriority             []ygot.Annotation                            `path:"config/@port-priority" ygotAnnotation:"true"`
	PortState                 E_OpenconfigSpanningTreeTypes_STP_PORT_STATE `path:"state/port-state" module:"openconfig-spanning-tree"`
	ΛPortState                []ygot.Annotation                            `path:"state/@port-state" ygotAnnotation:"true"`
	Role                      E_OpenconfigSpanningTreeTypes_STP_PORT_ROLE  `path:"state/role" module:"openconfig-spanning-tree"`
	ΛRole                     []ygot.Annotation                            `path:"state/@role" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Rstp_Interface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Rstp_Interface) IsYANGGoStruct() {}

// Stp_Rstp_Interface_Counters represents the /openconfig-spanning-tree/stp/rstp/interfaces/interface/state/counters YANG schema element.
type Stp_Rstp_Interface_Counters struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	BpduReceived  *uint64           `path:"bpdu-received" module:"openconfig-spanning-tree"`
	ΛBpduReceived []ygot.Annotation `path:"@bpdu-received" ygotAnnotation:"true"`
	BpduSent      *uint64           `path:"bpdu-sent" module:"openconfig-spanning-tree"`
	ΛBpduSent     []ygot.Annotation `path:"@bpdu-sent" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Rstp_Interface_Counters implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Rstp_Interface_Counters) IsYANGGoStruct() {}

// Stp_Vlan represents the /openconfig-spanning-tree/stp/rapid-pvst/vlan YANG schema element.
type Stp_Vlan struct {
	ΛMetadata                []ygot.Annotation              `path:"@" ygotAnnotation:"true"`
	BridgeAddress            *string                        `path:"state/bridge-address" module:"openconfig-spanning-tree"`
	ΛBridgeAddress           []ygot.Annotation              `path:"state/@bridge-address" ygotAnnotation:"true"`
	BridgePriority           *uint32                        `path:"config/bridge-priority" module:"openconfig-spanning-tree"`
	ΛBridgePriority          []ygot.Annotation              `path:"config/@bridge-priority" ygotAnnotation:"true"`
	DesignatedRootAddress    *string                        `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress   []ygot.Annotation              `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority   *uint32                        `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority  []ygot.Annotation              `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	ForwardingDelay          *uint8                         `path:"config/forwarding-delay" module:"openconfig-spanning-tree"`
	ΛForwardingDelay         []ygot.Annotation              `path:"config/@forwarding-delay" ygotAnnotation:"true"`
	HelloTime                *uint8                         `path:"config/hello-time" module:"openconfig-spanning-tree"`
	ΛHelloTime               []ygot.Annotation              `path:"config/@hello-time" ygotAnnotation:"true"`
	HoldCount                *uint8                         `path:"config/hold-count" module:"openconfig-spanning-tree"`
	ΛHoldCount               []ygot.Annotation              `path:"config/@hold-count" ygotAnnotation:"true"`
	HoldTime                 *uint8                         `path:"state/hold-time" module:"openconfig-spanning-tree"`
	ΛHoldTime                []ygot.Annotation              `path:"state/@hold-time" ygotAnnotation:"true"`
	Interface                map[string]*Stp_Vlan_Interface `path:"interfaces/interface" module:"openconfig-spanning-tree"`
	ΛInterface               []ygot.Annotation              `path:"interfaces/@interface" ygotAnnotation:"true"`
	MaxAge                   *uint8                         `path:"config/max-age" module:"openconfig-spanning-tree"`
	ΛMaxAge                  []ygot.Annotation              `path:"config/@max-age" ygotAnnotation:"true"`
	RootCost                 *uint32                        `path:"state/root-cost" module:"openconfig-spanning-tree"`
	ΛRootCost                []ygot.Annotation              `path:"state/@root-cost" ygotAnnotation:"true"`
	RootPort                 *uint16                        `path:"state/root-port" module:"openconfig-spanning-tree"`
	ΛRootPort                []ygot.Annotation              `path:"state/@root-port" ygotAnnotation:"true"`
	TimeSinceTopologyChange  *uint64                        `path:"state/time-since-topology-change" module:"openconfig-spanning-tree"`
	ΛTimeSinceTopologyChange []ygot.Annotation              `path:"state/@time-since-topology-change" ygotAnnotation:"true"`
	TopologyChanges          *uint64                        `path:"state/topology-changes" module:"openconfig-spanning-tree"`
	ΛTopologyChanges         []ygot.Annotation              `path:"state/@topology-changes" ygotAnnotation:"true"`
	VlanId                   *uint16                        `path:"config/vlan-id|vlan-id" module:"openconfig-spanning-tree"`
	ΛVlanId                  []ygot.Annotation              `path:"config/@vlan-id|@vlan-id" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Vlan implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Vlan) IsYANGGoStruct() {}

// Stp_Vlan_Interface represents the /openconfig-spanning-tree/stp/rapid-pvst/vlan/interfaces/interface YANG schema element.
type Stp_Vlan_Interface struct {
	ΛMetadata                 []ygot.Annotation                            `path:"@" ygotAnnotation:"true"`
	Cost                      *uint32                                      `path:"config/cost" module:"openconfig-spanning-tree"`
	ΛCost                     []ygot.Annotation                            `path:"config/@cost" ygotAnnotation:"true"`
	Counters                  *Stp_Vlan_Interface_Counters                 `path:"state/counters" module:"openconfig-spanning-tree"`
	ΛCounters                 []ygot.Annotation                            `path:"state/@counters" ygotAnnotation:"true"`
	DesignatedBridgeAddress   *string                                      `path:"state/designated-bridge-address" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgeAddress  []ygot.Annotation                            `path:"state/@designated-bridge-address" ygotAnnotation:"true"`
	DesignatedBridgePriority  *uint32                                      `path:"state/designated-bridge-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedBridgePriority []ygot.Annotation                            `path:"state/@designated-bridge-priority" ygotAnnotation:"true"`
	DesignatedCost            *uint32                                      `path:"state/designated-cost" module:"openconfig-spanning-tree"`
	ΛDesignatedCost           []ygot.Annotation                            `path:"state/@designated-cost" ygotAnnotation:"true"`
	DesignatedPortNum         *uint16                                      `path:"state/designated-port-num" module:"openconfig-spanning-tree"`
	ΛDesignatedPortNum        []ygot.Annotation                            `path:"state/@designated-port-num" ygotAnnotation:"true"`
	DesignatedPortPriority    *uint8                                       `path:"state/designated-port-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedPortPriority   []ygot.Annotation                            `path:"state/@designated-port-priority" ygotAnnotation:"true"`
	DesignatedRootAddress     *string                                      `path:"state/designated-root-address" module:"openconfig-spanning-tree"`
	ΛDesignatedRootAddress    []ygot.Annotation                            `path:"state/@designated-root-address" ygotAnnotation:"true"`
	DesignatedRootPriority    *uint32                                      `path:"state/designated-root-priority" module:"openconfig-spanning-tree"`
	ΛDesignatedRootPriority   []ygot.Annotation                            `path:"state/@designated-root-priority" ygotAnnotation:"true"`
	ForwardTransisitions      *uint64                                      `path:"state/forward-transisitions" module:"openconfig-spanning-tree"`
	ΛForwardTransisitions     []ygot.Annotation                            `path:"state/@forward-transisitions" ygotAnnotation:"true"`
	Name                      *string                                      `path:"config/name|name" module:"openconfig-spanning-tree"`
	ΛName                     []ygot.Annotation                            `path:"config/@name|@name" ygotAnnotation:"true"`
	PortNum                   *uint16                                      `path:"state/port-num" module:"openconfig-spanning-tree"`
	ΛPortNum                  []ygot.Annotation                            `path:"state/@port-num" ygotAnnotation:"true"`
	PortPriority              *uint8                                       `path:"config/port-priority" module:"openconfig-spanning-tree"`
	ΛPortPriority             []ygot.Annotation                            `path:"config/@port-priority" ygotAnnotation:"true"`
	PortState                 E_OpenconfigSpanningTreeTypes_STP_PORT_STATE `path:"state/port-state" module:"openconfig-spanning-tree"`
	ΛPortState                []ygot.Annotation                            `path:"state/@port-state" ygotAnnotation:"true"`
	Role                      E_OpenconfigSpanningTreeTypes_STP_PORT_ROLE  `path:"state/role" module:"openconfig-spanning-tree"`
	ΛRole                     []ygot.Annotation                            `path:"state/@role" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Vlan_Interface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Vlan_Interface) IsYANGGoStruct() {}

// Stp_Vlan_Interface_Counters represents the /openconfig-spanning-tree/stp/rapid-pvst/vlan/interfaces/interface/state/counters YANG schema element.
type Stp_Vlan_Interface_Counters struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	BpduReceived  *uint64           `path:"bpdu-received" module:"openconfig-spanning-tree"`
	ΛBpduReceived []ygot.Annotation `path:"@bpdu-received" ygotAnnotation:"true"`
	BpduSent      *uint64           `path:"bpdu-sent" module:"openconfig-spanning-tree"`
	ΛBpduSent     []ygot.Annotation `path:"@bpdu-sent" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Stp_Vlan_Interface_Counters implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Stp_Vlan_Interface_Counters) IsYANGGoStruct() {}

// System represents the /openconfig-system/system YANG schema element.
type System struct {
	ΛMetadata        []ygot.Annotation                      `path:"@" ygotAnnotation:"true"`
	Aaa              *System_Aaa                            `path:"aaa" module:"openconfig-system"`
	ΛAaa             []ygot.Annotation                      `path:"@aaa" ygotAnnotation:"true"`
	Alarm            map[string]*System_Alarm               `path:"alarms/alarm" module:"openconfig-system"`
	ΛAlarm           []ygot.Annotation                      `path:"alarms/@alarm" ygotAnnotation:"true"`
	BootTime         *uint64                                `path:"state/boot-time" module:"openconfig-system"`
	ΛBootTime        []ygot.Annotation                      `path:"state/@boot-time" ygotAnnotation:"true"`
	Clock            *System_Clock                          `path:"clock" module:"openconfig-system"`
	ΛClock           []ygot.Annotation                      `path:"@clock" ygotAnnotation:"true"`
	Cpu              map[System_Cpu_Index_Union]*System_Cpu `path:"cpus/cpu" module:"openconfig-system"`
	ΛCpu             []ygot.Annotation                      `path:"cpus/@cpu" ygotAnnotation:"true"`
	CurrentDatetime  *string                                `path:"state/current-datetime" module:"openconfig-system"`
	ΛCurrentDatetime []ygot.Annotation                      `path:"state/@current-datetime" ygotAnnotation:"true"`
	Dns              *System_Dns                            `path:"dns" module:"openconfig-system"`
	ΛDns             []ygot.Annotation                      `path:"@dns" ygotAnnotation:"true"`
	DomainName       *string                                `path:"config/domain-name" module:"openconfig-system"`
	ΛDomainName      []ygot.Annotation                      `path:"config/@domain-name" ygotAnnotation:"true"`
	Hostname         *string                                `path:"config/hostname" module:"openconfig-system"`
	ΛHostname        []ygot.Annotation                      `path:"config/@hostname" ygotAnnotation:"true"`
	Logging          *System_Logging                        `path:"logging" module:"openconfig-system"`
	ΛLogging         []ygot.Annotation                      `path:"@logging" ygotAnnotation:"true"`
	LoginBanner      *string                                `path:"config/login-banner" module:"openconfig-system"`
	ΛLoginBanner     []ygot.Annotation                      `path:"config/@login-banner" ygotAnnotation:"true"`
	Memory           *System_Memory                         `path:"memory" module:"openconfig-system"`
	ΛMemory          []ygot.Annotation                      `path:"@memory" ygotAnnotation:"true"`
	MotdBanner       *string                                `path:"config/motd-banner" module:"openconfig-system"`
	ΛMotdBanner      []ygot.Annotation                      `path:"config/@motd-banner" ygotAnnotation:"true"`
	Ntp              *System_Ntp                            `path:"ntp" module:"openconfig-system"`
	ΛNtp             []ygot.Annotation                      `path:"@ntp" ygotAnnotation:"true"`
	Process          map[uint64]*System_Process             `path:"processes/process" module:"openconfig-system"`
	ΛProcess         []ygot.Annotation                      `path:"processes/@process" ygotAnnotation:"true"`
	SshServer        *System_SshServer                      `path:"ssh-server" module:"openconfig-system"`
	ΛSshServer       []ygot.Annotation                      `path:"@ssh-server" ygotAnnotation:"true"`
	TelnetServer     *System_TelnetServer                   `path:"telnet-server" module:"openconfig-system"`
	ΛTelnetServer    []ygot.Annotation                      `path:"@telnet-server" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System) IsYANGGoStruct() {}

// System_Aaa represents the /openconfig-system/system/aaa YANG schema element.
type System_Aaa struct {
	ΛMetadata       []ygot.Annotation                  `path:"@" ygotAnnotation:"true"`
	Accounting      *System_Aaa_Accounting             `path:"accounting" module:"openconfig-system"`
	ΛAccounting     []ygot.Annotation                  `path:"@accounting" ygotAnnotation:"true"`
	Authentication  *System_Aaa_Authentication         `path:"authentication" module:"openconfig-system"`
	ΛAuthentication []ygot.Annotation                  `path:"@authentication" ygotAnnotation:"true"`
	Authorization   *System_Aaa_Authorization          `path:"authorization" module:"openconfig-system"`
	ΛAuthorization  []ygot.Annotation                  `path:"@authorization" ygotAnnotation:"true"`
	ServerGroup     map[string]*System_Aaa_ServerGroup `path:"server-groups/server-group" module:"openconfig-system"`
	ΛServerGroup    []ygot.Annotation                  `path:"server-groups/@server-group" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa) IsYANGGoStruct() {}

// System_Aaa_Accounting represents the /openconfig-system/system/aaa/accounting YANG schema element.
type System_Aaa_Accounting struct {
	ΛMetadata         []ygot.Annotation                                                               `path:"@" ygotAnnotation:"true"`
	AccountingMethod  []System_Aaa_Accounting_AccountingMethod_Union                                  `path:"config/accounting-method" module:"openconfig-system"`
	ΛAccountingMethod []ygot.Annotation                                                               `path:"config/@accounting-method" ygotAnnotation:"true"`
	Event             map[E_OpenconfigAaaTypes_AAA_ACCOUNTING_EVENT_TYPE]*System_Aaa_Accounting_Event `path:"events/event" module:"openconfig-system"`
	ΛEvent            []ygot.Annotation                                                               `path:"events/@event" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Accounting implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Accounting) IsYANGGoStruct() {}

// System_Aaa_Accounting_Event represents the /openconfig-system/system/aaa/accounting/events/event YANG schema element.
type System_Aaa_Accounting_Event struct {
	ΛMetadata  []ygot.Annotation                              `path:"@" ygotAnnotation:"true"`
	EventType  E_OpenconfigAaaTypes_AAA_ACCOUNTING_EVENT_TYPE `path:"config/event-type|event-type" module:"openconfig-system"`
	ΛEventType []ygot.Annotation                              `path:"config/@event-type|@event-type" ygotAnnotation:"true"`
	Record     E_OpenconfigAaa_Event_Record                   `path:"config/record" module:"openconfig-system"`
	ΛRecord    []ygot.Annotation                              `path:"config/@record" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Accounting_Event implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Accounting_Event) IsYANGGoStruct() {}

// System_Aaa_Authentication represents the /openconfig-system/system/aaa/authentication YANG schema element.
type System_Aaa_Authentication struct {
	ΛMetadata             []ygot.Annotation                                      `path:"@" ygotAnnotation:"true"`
	AdminUser             *System_Aaa_Authentication_AdminUser                   `path:"admin-user" module:"openconfig-system"`
	ΛAdminUser            []ygot.Annotation                                      `path:"@admin-user" ygotAnnotation:"true"`
	AuthenticationMethod  []System_Aaa_Authentication_AuthenticationMethod_Union `path:"config/authentication-method" module:"openconfig-system"`
	ΛAuthenticationMethod []ygot.Annotation                                      `path:"config/@authentication-method" ygotAnnotation:"true"`
	User                  map[string]*System_Aaa_Authentication_User             `path:"users/user" module:"openconfig-system"`
	ΛUser                 []ygot.Annotation                                      `path:"users/@user" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Authentication implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Authentication) IsYANGGoStruct() {}

// System_Aaa_Authentication_AdminUser represents the /openconfig-system/system/aaa/authentication/admin-user YANG schema element.
type System_Aaa_Authentication_AdminUser struct {
	ΛMetadata            []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	AdminPassword        *string           `path:"config/admin-password" module:"openconfig-system"`
	ΛAdminPassword       []ygot.Annotation `path:"config/@admin-password" ygotAnnotation:"true"`
	AdminPasswordHashed  *string           `path:"config/admin-password-hashed" module:"openconfig-system"`
	ΛAdminPasswordHashed []ygot.Annotation `path:"config/@admin-password-hashed" ygotAnnotation:"true"`
	AdminUsername        *string           `path:"state/admin-username" module:"openconfig-system"`
	ΛAdminUsername       []ygot.Annotation `path:"state/@admin-username" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Authentication_AdminUser implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Authentication_AdminUser) IsYANGGoStruct() {}

// System_Aaa_Authentication_User represents the /openconfig-system/system/aaa/authentication/users/user YANG schema element.
type System_Aaa_Authentication_User struct {
	ΛMetadata       []ygot.Annotation                         `path:"@" ygotAnnotation:"true"`
	Password        *string                                   `path:"config/password" module:"openconfig-system"`
	ΛPassword       []ygot.Annotation                         `path:"config/@password" ygotAnnotation:"true"`
	PasswordHashed  *string                                   `path:"config/password-hashed" module:"openconfig-system"`
	ΛPasswordHashed []ygot.Annotation                         `path:"config/@password-hashed" ygotAnnotation:"true"`
	Role            System_Aaa_Authentication_User_Role_Union `path:"config/role" module:"openconfig-system"`
	ΛRole           []ygot.Annotation                         `path:"config/@role" ygotAnnotation:"true"`
	SshKey          *string                                   `path:"config/ssh-key" module:"openconfig-system"`
	ΛSshKey         []ygot.Annotation                         `path:"config/@ssh-key" ygotAnnotation:"true"`
	Username        *string                                   `path:"config/username|username" module:"openconfig-system"`
	ΛUsername       []ygot.Annotation                         `path:"config/@username|@username" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Authentication_User implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Authentication_User) IsYANGGoStruct() {}

// System_Aaa_Authorization represents the /openconfig-system/system/aaa/authorization YANG schema element.
type System_Aaa_Authorization struct {
	ΛMetadata            []ygot.Annotation                                                                     `path:"@" ygotAnnotation:"true"`
	AuthorizationMethod  []System_Aaa_Authorization_AuthorizationMethod_Union                                  `path:"config/authorization-method" module:"openconfig-system"`
	ΛAuthorizationMethod []ygot.Annotation                                                                     `path:"config/@authorization-method" ygotAnnotation:"true"`
	Event                map[E_OpenconfigAaaTypes_AAA_AUTHORIZATION_EVENT_TYPE]*System_Aaa_Authorization_Event `path:"events/event" module:"openconfig-system"`
	ΛEvent               []ygot.Annotation                                                                     `path:"events/@event" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Authorization implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Authorization) IsYANGGoStruct() {}

// System_Aaa_Authorization_Event represents the /openconfig-system/system/aaa/authorization/events/event YANG schema element.
type System_Aaa_Authorization_Event struct {
	ΛMetadata  []ygot.Annotation                                 `path:"@" ygotAnnotation:"true"`
	EventType  E_OpenconfigAaaTypes_AAA_AUTHORIZATION_EVENT_TYPE `path:"config/event-type|event-type" module:"openconfig-system"`
	ΛEventType []ygot.Annotation                                 `path:"config/@event-type|@event-type" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_Authorization_Event implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_Authorization_Event) IsYANGGoStruct() {}

// System_Aaa_ServerGroup represents the /openconfig-system/system/aaa/server-groups/server-group YANG schema element.
type System_Aaa_ServerGroup struct {
	ΛMetadata []ygot.Annotation                         `path:"@" ygotAnnotation:"true"`
	Name      *string                                   `path:"config/name|name" module:"openconfig-system"`
	ΛName     []ygot.Annotation                         `path:"config/@name|@name" ygotAnnotation:"true"`
	Server    map[string]*System_Aaa_ServerGroup_Server `path:"servers/server" module:"openconfig-system"`
	ΛServer   []ygot.Annotation                         `path:"servers/@server" ygotAnnotation:"true"`
	Type      E_OpenconfigAaaTypes_AAA_SERVER_TYPE      `path:"config/type" module:"openconfig-system"`
	ΛType     []ygot.Annotation                         `path:"config/@type" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_ServerGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_ServerGroup) IsYANGGoStruct() {}

// System_Aaa_ServerGroup_Server represents the /openconfig-system/system/aaa/server-groups/server-group/servers/server YANG schema element.
type System_Aaa_ServerGroup_Server struct {
	ΛMetadata           []ygot.Annotation                     `path:"@" ygotAnnotation:"true"`
	Address             *string                               `path:"config/address|address" module:"openconfig-system"`
	ΛAddress            []ygot.Annotation                     `path:"config/@address|@address" ygotAnnotation:"true"`
	ConnectionAborts    *uint64                               `path:"state/connection-aborts" module:"openconfig-system"`
	ΛConnectionAborts   []ygot.Annotation                     `path:"state/@connection-aborts" ygotAnnotation:"true"`
	ConnectionCloses    *uint64                               `path:"state/connection-closes" module:"openconfig-system"`
	ΛConnectionCloses   []ygot.Annotation                     `path:"state/@connection-closes" ygotAnnotation:"true"`
	ConnectionFailures  *uint64                               `path:"state/connection-failures" module:"openconfig-system"`
	ΛConnectionFailures []ygot.Annotation                     `path:"state/@connection-failures" ygotAnnotation:"true"`
	ConnectionOpens     *uint64                               `path:"state/connection-opens" module:"openconfig-system"`
	ΛConnectionOpens    []ygot.Annotation                     `path:"state/@connection-opens" ygotAnnotation:"true"`
	ConnectionTimeouts  *uint64                               `path:"state/connection-timeouts" module:"openconfig-system"`
	ΛConnectionTimeouts []ygot.Annotation                     `path:"state/@connection-timeouts" ygotAnnotation:"true"`
	ErrorsReceived      *uint64                               `path:"state/errors-received" module:"openconfig-system"`
	ΛErrorsReceived     []ygot.Annotation                     `path:"state/@errors-received" ygotAnnotation:"true"`
	MessagesReceived    *uint64                               `path:"state/messages-received" module:"openconfig-system"`
	ΛMessagesReceived   []ygot.Annotation                     `path:"state/@messages-received" ygotAnnotation:"true"`
	MessagesSent        *uint64                               `path:"state/messages-sent" module:"openconfig-system"`
	ΛMessagesSent       []ygot.Annotation                     `path:"state/@messages-sent" ygotAnnotation:"true"`
	Name                *string                               `path:"config/name" module:"openconfig-system"`
	ΛName               []ygot.Annotation                     `path:"config/@name" ygotAnnotation:"true"`
	Radius              *System_Aaa_ServerGroup_Server_Radius `path:"radius" module:"openconfig-system"`
	ΛRadius             []ygot.Annotation                     `path:"@radius" ygotAnnotation:"true"`
	Tacacs              *System_Aaa_ServerGroup_Server_Tacacs `path:"tacacs" module:"openconfig-system"`
	ΛTacacs             []ygot.Annotation                     `path:"@tacacs" ygotAnnotation:"true"`
	Timeout             *uint16                               `path:"config/timeout" module:"openconfig-system"`
	ΛTimeout            []ygot.Annotation                     `path:"config/@timeout" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_ServerGroup_Server implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_ServerGroup_Server) IsYANGGoStruct() {}

// System_Aaa_ServerGroup_Server_Radius represents the /openconfig-system/system/aaa/server-groups/server-group/servers/server/radius YANG schema element.
type System_Aaa_ServerGroup_Server_Radius struct {
	ΛMetadata           []ygot.Annotation                              `path:"@" ygotAnnotation:"true"`
	AcctPort            *uint16                                        `path:"config/acct-port" module:"openconfig-system"`
	ΛAcctPort           []ygot.Annotation                              `path:"config/@acct-port" ygotAnnotation:"true"`
	AuthPort            *uint16                                        `path:"config/auth-port" module:"openconfig-system"`
	ΛAuthPort           []ygot.Annotation                              `path:"config/@auth-port" ygotAnnotation:"true"`
	Counters            *System_Aaa_ServerGroup_Server_Radius_Counters `path:"state/counters" module:"openconfig-system"`
	ΛCounters           []ygot.Annotation                              `path:"state/@counters" ygotAnnotation:"true"`
	RetransmitAttempts  *uint8                                         `path:"config/retransmit-attempts" module:"openconfig-system"`
	ΛRetransmitAttempts []ygot.Annotation                              `path:"config/@retransmit-attempts" ygotAnnotation:"true"`
	SecretKey           *string                                        `path:"config/secret-key" module:"openconfig-system"`
	ΛSecretKey          []ygot.Annotation                              `path:"config/@secret-key" ygotAnnotation:"true"`
	SourceAddress       *string                                        `path:"config/source-address" module:"openconfig-system"`
	ΛSourceAddress      []ygot.Annotation                              `path:"config/@source-address" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_ServerGroup_Server_Radius implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_ServerGroup_Server_Radius) IsYANGGoStruct() {}

// System_Aaa_ServerGroup_Server_Radius_Counters represents the /openconfig-system/system/aaa/server-groups/server-group/servers/server/radius/state/counters YANG schema element.
type System_Aaa_ServerGroup_Server_Radius_Counters struct {
	ΛMetadata              []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	AccessAccepts          *uint64           `path:"access-accepts" module:"openconfig-system"`
	ΛAccessAccepts         []ygot.Annotation `path:"@access-accepts" ygotAnnotation:"true"`
	AccessRejects          *uint64           `path:"access-rejects" module:"openconfig-system"`
	ΛAccessRejects         []ygot.Annotation `path:"@access-rejects" ygotAnnotation:"true"`
	RetriedAccessRequests  *uint64           `path:"retried-access-requests" module:"openconfig-system"`
	ΛRetriedAccessRequests []ygot.Annotation `path:"@retried-access-requests" ygotAnnotation:"true"`
	TimeoutAccessRequests  *uint64           `path:"timeout-access-requests" module:"openconfig-system"`
	ΛTimeoutAccessRequests []ygot.Annotation `path:"@timeout-access-requests" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_ServerGroup_Server_Radius_Counters implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_ServerGroup_Server_Radius_Counters) IsYANGGoStruct() {}

// System_Aaa_ServerGroup_Server_Tacacs represents the /openconfig-system/system/aaa/server-groups/server-group/servers/server/tacacs YANG schema element.
type System_Aaa_ServerGroup_Server_Tacacs struct {
	ΛMetadata      []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Port           *uint16           `path:"config/port" module:"openconfig-system"`
	ΛPort          []ygot.Annotation `path:"config/@port" ygotAnnotation:"true"`
	SecretKey      *string           `path:"config/secret-key" module:"openconfig-system"`
	ΛSecretKey     []ygot.Annotation `path:"config/@secret-key" ygotAnnotation:"true"`
	SourceAddress  *string           `path:"config/source-address" module:"openconfig-system"`
	ΛSourceAddress []ygot.Annotation `path:"config/@source-address" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Aaa_ServerGroup_Server_Tacacs implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Aaa_ServerGroup_Server_Tacacs) IsYANGGoStruct() {}

// System_Alarm represents the /openconfig-system/system/alarms/alarm YANG schema element.
type System_Alarm struct {
	ΛMetadata    []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	Id           *string                                          `path:"state/id|id" module:"openconfig-system"`
	ΛId          []ygot.Annotation                                `path:"state/@id|@id" ygotAnnotation:"true"`
	Resource     *string                                          `path:"state/resource" module:"openconfig-system"`
	ΛResource    []ygot.Annotation                                `path:"state/@resource" ygotAnnotation:"true"`
	Severity     E_OpenconfigAlarmTypes_OPENCONFIG_ALARM_SEVERITY `path:"state/severity" module:"openconfig-system"`
	ΛSeverity    []ygot.Annotation                                `path:"state/@severity" ygotAnnotation:"true"`
	Text         *string                                          `path:"state/text" module:"openconfig-system"`
	ΛText        []ygot.Annotation                                `path:"state/@text" ygotAnnotation:"true"`
	TimeCreated  *uint64                                          `path:"state/time-created" module:"openconfig-system"`
	ΛTimeCreated []ygot.Annotation                                `path:"state/@time-created" ygotAnnotation:"true"`
	TypeId       System_Alarm_TypeId_Union                        `path:"state/type-id" module:"openconfig-system"`
	ΛTypeId      []ygot.Annotation                                `path:"state/@type-id" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Alarm implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Alarm) IsYANGGoStruct() {}

// System_Clock represents the /openconfig-system/system/clock YANG schema element.
type System_Clock struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	TimezoneName  *string           `path:"config/timezone-name" module:"openconfig-system"`
	ΛTimezoneName []ygot.Annotation `path:"config/@timezone-name" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Clock implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Clock) IsYANGGoStruct() {}

// System_Cpu represents the /openconfig-system/system/cpus/cpu YANG schema element.
type System_Cpu struct {
	ΛMetadata          []ygot.Annotation             `path:"@" ygotAnnotation:"true"`
	HardwareInterrupt  *System_Cpu_HardwareInterrupt `path:"state/hardware-interrupt" module:"openconfig-system"`
	ΛHardwareInterrupt []ygot.Annotation             `path:"state/@hardware-interrupt" ygotAnnotation:"true"`
	Idle               *System_Cpu_Idle              `path:"state/idle" module:"openconfig-system"`
	ΛIdle              []ygot.Annotation             `path:"state/@idle" ygotAnnotation:"true"`
	Index              System_Cpu_Index_Union        `path:"state/index|index" module:"openconfig-system"`
	ΛIndex             []ygot.Annotation             `path:"state/@index|@index" ygotAnnotation:"true"`
	Kernel             *System_Cpu_Kernel            `path:"state/kernel" module:"openconfig-system"`
	ΛKernel            []ygot.Annotation             `path:"state/@kernel" ygotAnnotation:"true"`
	Nice               *System_Cpu_Nice              `path:"state/nice" module:"openconfig-system"`
	ΛNice              []ygot.Annotation             `path:"state/@nice" ygotAnnotation:"true"`
	SoftwareInterrupt  *System_Cpu_SoftwareInterrupt `path:"state/software-interrupt" module:"openconfig-system"`
	ΛSoftwareInterrupt []ygot.Annotation             `path:"state/@software-interrupt" ygotAnnotation:"true"`
	Total              *System_Cpu_Total             `path:"state/total" module:"openconfig-system"`
	ΛTotal             []ygot.Annotation             `path:"state/@total" ygotAnnotation:"true"`
	User               *System_Cpu_User              `path:"state/user" module:"openconfig-system"`
	ΛUser              []ygot.Annotation             `path:"state/@user" ygotAnnotation:"true"`
	Wait               *System_Cpu_Wait              `path:"state/wait" module:"openconfig-system"`
	ΛWait              []ygot.Annotation             `path:"state/@wait" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu) IsYANGGoStruct() {}

// System_Cpu_HardwareInterrupt represents the /openconfig-system/system/cpus/cpu/state/hardware-interrupt YANG schema element.
type System_Cpu_HardwareInterrupt struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_HardwareInterrupt implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_HardwareInterrupt) IsYANGGoStruct() {}

// System_Cpu_Idle represents the /openconfig-system/system/cpus/cpu/state/idle YANG schema element.
type System_Cpu_Idle struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_Idle implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_Idle) IsYANGGoStruct() {}

// System_Cpu_Kernel represents the /openconfig-system/system/cpus/cpu/state/kernel YANG schema element.
type System_Cpu_Kernel struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_Kernel implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_Kernel) IsYANGGoStruct() {}

// System_Cpu_Nice represents the /openconfig-system/system/cpus/cpu/state/nice YANG schema element.
type System_Cpu_Nice struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_Nice implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_Nice) IsYANGGoStruct() {}

// System_Cpu_SoftwareInterrupt represents the /openconfig-system/system/cpus/cpu/state/software-interrupt YANG schema element.
type System_Cpu_SoftwareInterrupt struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_SoftwareInterrupt implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_SoftwareInterrupt) IsYANGGoStruct() {}

// System_Cpu_Total represents the /openconfig-system/system/cpus/cpu/state/total YANG schema element.
type System_Cpu_Total struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_Total implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_Total) IsYANGGoStruct() {}

// System_Cpu_User represents the /openconfig-system/system/cpus/cpu/state/user YANG schema element.
type System_Cpu_User struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_User implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_User) IsYANGGoStruct() {}

// System_Cpu_Wait represents the /openconfig-system/system/cpus/cpu/state/wait YANG schema element.
type System_Cpu_Wait struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *uint8            `path:"avg" module:"openconfig-system"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *uint8            `path:"instant" module:"openconfig-system"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-system"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *uint8            `path:"max" module:"openconfig-system"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *uint8            `path:"min" module:"openconfig-system"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Cpu_Wait implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Cpu_Wait) IsYANGGoStruct() {}

// System_Dns represents the /openconfig-system/system/dns YANG schema element.
type System_Dns struct {
	ΛMetadata  []ygot.Annotation                `path:"@" ygotAnnotation:"true"`
	HostEntry  map[string]*System_Dns_HostEntry `path:"host-entries/host-entry" module:"openconfig-system"`
	ΛHostEntry []ygot.Annotation                `path:"host-entries/@host-entry" ygotAnnotation:"true"`
	Search     []string                         `path:"config/search" module:"openconfig-system"`
	ΛSearch    []ygot.Annotation                `path:"config/@search" ygotAnnotation:"true"`
	Server     map[string]*System_Dns_Server    `path:"servers/server" module:"openconfig-system"`
	ΛServer    []ygot.Annotation                `path:"servers/@server" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Dns implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Dns) IsYANGGoStruct() {}

// System_Dns_HostEntry represents the /openconfig-system/system/dns/host-entries/host-entry YANG schema element.
type System_Dns_HostEntry struct {
	ΛMetadata    []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Alias        []string          `path:"config/alias" module:"openconfig-system"`
	ΛAlias       []ygot.Annotation `path:"config/@alias" ygotAnnotation:"true"`
	Hostname     *string           `path:"config/hostname|hostname" module:"openconfig-system"`
	ΛHostname    []ygot.Annotation `path:"config/@hostname|@hostname" ygotAnnotation:"true"`
	Ipv4Address  []string          `path:"config/ipv4-address" module:"openconfig-system"`
	ΛIpv4Address []ygot.Annotation `path:"config/@ipv4-address" ygotAnnotation:"true"`
	Ipv6Address  []string          `path:"config/ipv6-address" module:"openconfig-system"`
	ΛIpv6Address []ygot.Annotation `path:"config/@ipv6-address" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Dns_HostEntry implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Dns_HostEntry) IsYANGGoStruct() {}

// System_Dns_Server represents the /openconfig-system/system/dns/servers/server YANG schema element.
type System_Dns_Server struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Address   *string           `path:"config/address|address" module:"openconfig-system"`
	ΛAddress  []ygot.Annotation `path:"config/@address|@address" ygotAnnotation:"true"`
	Port      *uint16           `path:"config/port" module:"openconfig-system"`
	ΛPort     []ygot.Annotation `path:"config/@port" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Dns_Server implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Dns_Server) IsYANGGoStruct() {}

// System_Logging represents the /openconfig-system/system/logging YANG schema element.
type System_Logging struct {
	ΛMetadata     []ygot.Annotation                       `path:"@" ygotAnnotation:"true"`
	Console       *System_Logging_Console                 `path:"console" module:"openconfig-system"`
	ΛConsole      []ygot.Annotation                       `path:"@console" ygotAnnotation:"true"`
	RemoteServer  map[string]*System_Logging_RemoteServer `path:"remote-servers/remote-server" module:"openconfig-system"`
	ΛRemoteServer []ygot.Annotation                       `path:"remote-servers/@remote-server" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Logging implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Logging) IsYANGGoStruct() {}

// System_Logging_Console represents the /openconfig-system/system/logging/console YANG schema element.
type System_Logging_Console struct {
	ΛMetadata []ygot.Annotation                                                        `path:"@" ygotAnnotation:"true"`
	Selector  map[System_Logging_Console_Selector_Key]*System_Logging_Console_Selector `path:"selectors/selector" module:"openconfig-system"`
	ΛSelector []ygot.Annotation                                                        `path:"selectors/@selector" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Logging_Console implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Logging_Console) IsYANGGoStruct() {}

// System_Logging_Console_Selector_Key represents the key for list Selector of element /openconfig-system/system/logging/console.
type System_Logging_Console_Selector_Key struct {
	Facility E_OpenconfigSystemLogging_SYSLOG_FACILITY `path:"facility"`
	Severity E_OpenconfigSystemLogging_SyslogSeverity  `path:"severity"`
}

// System_Logging_Console_Selector represents the /openconfig-system/system/logging/console/selectors/selector YANG schema element.
type System_Logging_Console_Selector struct {
	ΛMetadata []ygot.Annotation                         `path:"@" ygotAnnotation:"true"`
	Facility  E_OpenconfigSystemLogging_SYSLOG_FACILITY `path:"config/facility|facility" module:"openconfig-system"`
	ΛFacility []ygot.Annotation                         `path:"config/@facility|@facility" ygotAnnotation:"true"`
	Severity  E_OpenconfigSystemLogging_SyslogSeverity  `path:"config/severity|severity" module:"openconfig-system"`
	ΛSeverity []ygot.Annotation                         `path:"config/@severity|@severity" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Logging_Console_Selector implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Logging_Console_Selector) IsYANGGoStruct() {}

// System_Logging_RemoteServer represents the /openconfig-system/system/logging/remote-servers/remote-server YANG schema element.
type System_Logging_RemoteServer struct {
	ΛMetadata      []ygot.Annotation                                                                  `path:"@" ygotAnnotation:"true"`
	Host           *string                                                                            `path:"config/host|host" module:"openconfig-system"`
	ΛHost          []ygot.Annotation                                                                  `path:"config/@host|@host" ygotAnnotation:"true"`
	RemotePort     *uint16                                                                            `path:"config/remote-port" module:"openconfig-system"`
	ΛRemotePort    []ygot.Annotation                                                                  `path:"config/@remote-port" ygotAnnotation:"true"`
	Selector       map[System_Logging_RemoteServer_Selector_Key]*System_Logging_RemoteServer_Selector `path:"selectors/selector" module:"openconfig-system"`
	ΛSelector      []ygot.Annotation                                                                  `path:"selectors/@selector" ygotAnnotation:"true"`
	SourceAddress  *string                                                                            `path:"config/source-address" module:"openconfig-system"`
	ΛSourceAddress []ygot.Annotation                                                                  `path:"config/@source-address" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Logging_RemoteServer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Logging_RemoteServer) IsYANGGoStruct() {}

// System_Logging_RemoteServer_Selector_Key represents the key for list Selector of element /openconfig-system/system/logging/remote-servers/remote-server.
type System_Logging_RemoteServer_Selector_Key struct {
	Facility E_OpenconfigSystemLogging_SYSLOG_FACILITY `path:"facility"`
	Severity E_OpenconfigSystemLogging_SyslogSeverity  `path:"severity"`
}

// System_Logging_RemoteServer_Selector represents the /openconfig-system/system/logging/remote-servers/remote-server/selectors/selector YANG schema element.
type System_Logging_RemoteServer_Selector struct {
	ΛMetadata []ygot.Annotation                         `path:"@" ygotAnnotation:"true"`
	Facility  E_OpenconfigSystemLogging_SYSLOG_FACILITY `path:"config/facility|facility" module:"openconfig-system"`
	ΛFacility []ygot.Annotation                         `path:"config/@facility|@facility" ygotAnnotation:"true"`
	Severity  E_OpenconfigSystemLogging_SyslogSeverity  `path:"config/severity|severity" module:"openconfig-system"`
	ΛSeverity []ygot.Annotation                         `path:"config/@severity|@severity" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Logging_RemoteServer_Selector implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Logging_RemoteServer_Selector) IsYANGGoStruct() {}

// System_Memory represents the /openconfig-system/system/memory YANG schema element.
type System_Memory struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Physical  *uint64           `path:"state/physical" module:"openconfig-system"`
	ΛPhysical []ygot.Annotation `path:"state/@physical" ygotAnnotation:"true"`
	Reserved  *uint64           `path:"state/reserved" module:"openconfig-system"`
	ΛReserved []ygot.Annotation `path:"state/@reserved" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Memory implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Memory) IsYANGGoStruct() {}

// System_Ntp represents the /openconfig-system/system/ntp YANG schema element.
type System_Ntp struct {
	ΛMetadata         []ygot.Annotation             `path:"@" ygotAnnotation:"true"`
	AuthMismatch      *uint64                       `path:"state/auth-mismatch" module:"openconfig-system"`
	ΛAuthMismatch     []ygot.Annotation             `path:"state/@auth-mismatch" ygotAnnotation:"true"`
	EnableNtpAuth     *bool                         `path:"config/enable-ntp-auth" module:"openconfig-system"`
	ΛEnableNtpAuth    []ygot.Annotation             `path:"config/@enable-ntp-auth" ygotAnnotation:"true"`
	Enabled           *bool                         `path:"config/enabled" module:"openconfig-system"`
	ΛEnabled          []ygot.Annotation             `path:"config/@enabled" ygotAnnotation:"true"`
	NtpKey            map[uint16]*System_Ntp_NtpKey `path:"ntp-keys/ntp-key" module:"openconfig-system"`
	ΛNtpKey           []ygot.Annotation             `path:"ntp-keys/@ntp-key" ygotAnnotation:"true"`
	NtpSourceAddress  *string                       `path:"config/ntp-source-address" module:"openconfig-system"`
	ΛNtpSourceAddress []ygot.Annotation             `path:"config/@ntp-source-address" ygotAnnotation:"true"`
	Server            map[string]*System_Ntp_Server `path:"servers/server" module:"openconfig-system"`
	ΛServer           []ygot.Annotation             `path:"servers/@server" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Ntp implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Ntp) IsYANGGoStruct() {}

// System_Ntp_NtpKey represents the /openconfig-system/system/ntp/ntp-keys/ntp-key YANG schema element.
type System_Ntp_NtpKey struct {
	ΛMetadata []ygot.Annotation                `path:"@" ygotAnnotation:"true"`
	KeyId     *uint16                          `path:"config/key-id|key-id" module:"openconfig-system"`
	ΛKeyId    []ygot.Annotation                `path:"config/@key-id|@key-id" ygotAnnotation:"true"`
	KeyType   E_OpenconfigSystem_NTP_AUTH_TYPE `path:"config/key-type" module:"openconfig-system"`
	ΛKeyType  []ygot.Annotation                `path:"config/@key-type" ygotAnnotation:"true"`
	KeyValue  *string                          `path:"config/key-value" module:"openconfig-system"`
	ΛKeyValue []ygot.Annotation                `path:"config/@key-value" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Ntp_NtpKey implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Ntp_NtpKey) IsYANGGoStruct() {}

// System_Ntp_Server represents the /openconfig-system/system/ntp/servers/server YANG schema element.
type System_Ntp_Server struct {
	ΛMetadata        []ygot.Annotation                         `path:"@" ygotAnnotation:"true"`
	Address          *string                                   `path:"config/address|address" module:"openconfig-system"`
	ΛAddress         []ygot.Annotation                         `path:"config/@address|@address" ygotAnnotation:"true"`
	AssociationType  E_OpenconfigSystem_Server_AssociationType `path:"config/association-type" module:"openconfig-system"`
	ΛAssociationType []ygot.Annotation                         `path:"config/@association-type" ygotAnnotation:"true"`
	Iburst           *bool                                     `path:"config/iburst" module:"openconfig-system"`
	ΛIburst          []ygot.Annotation                         `path:"config/@iburst" ygotAnnotation:"true"`
	Offset           *uint64                                   `path:"state/offset" module:"openconfig-system"`
	ΛOffset          []ygot.Annotation                         `path:"state/@offset" ygotAnnotation:"true"`
	PollInterval     *uint32                                   `path:"state/poll-interval" module:"openconfig-system"`
	ΛPollInterval    []ygot.Annotation                         `path:"state/@poll-interval" ygotAnnotation:"true"`
	Port             *uint16                                   `path:"config/port" module:"openconfig-system"`
	ΛPort            []ygot.Annotation                         `path:"config/@port" ygotAnnotation:"true"`
	Prefer           *bool                                     `path:"config/prefer" module:"openconfig-system"`
	ΛPrefer          []ygot.Annotation                         `path:"config/@prefer" ygotAnnotation:"true"`
	RootDelay        *uint32                                   `path:"state/root-delay" module:"openconfig-system"`
	ΛRootDelay       []ygot.Annotation                         `path:"state/@root-delay" ygotAnnotation:"true"`
	RootDispersion   *uint64                                   `path:"state/root-dispersion" module:"openconfig-system"`
	ΛRootDispersion  []ygot.Annotation                         `path:"state/@root-dispersion" ygotAnnotation:"true"`
	Stratum          *uint8                                    `path:"state/stratum" module:"openconfig-system"`
	ΛStratum         []ygot.Annotation                         `path:"state/@stratum" ygotAnnotation:"true"`
	Version          *uint8                                    `path:"config/version" module:"openconfig-system"`
	ΛVersion         []ygot.Annotation                         `path:"config/@version" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Ntp_Server implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Ntp_Server) IsYANGGoStruct() {}

// System_Process represents the /openconfig-system/system/processes/process YANG schema element.
type System_Process struct {
	ΛMetadata          []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Args               []string          `path:"state/args" module:"openconfig-system"`
	ΛArgs              []ygot.Annotation `path:"state/@args" ygotAnnotation:"true"`
	CpuUsageSystem     *uint64           `path:"state/cpu-usage-system" module:"openconfig-system"`
	ΛCpuUsageSystem    []ygot.Annotation `path:"state/@cpu-usage-system" ygotAnnotation:"true"`
	CpuUsageUser       *uint64           `path:"state/cpu-usage-user" module:"openconfig-system"`
	ΛCpuUsageUser      []ygot.Annotation `path:"state/@cpu-usage-user" ygotAnnotation:"true"`
	CpuUtilization     *uint8            `path:"state/cpu-utilization" module:"openconfig-system"`
	ΛCpuUtilization    []ygot.Annotation `path:"state/@cpu-utilization" ygotAnnotation:"true"`
	MemoryUsage        *uint64           `path:"state/memory-usage" module:"openconfig-system"`
	ΛMemoryUsage       []ygot.Annotation `path:"state/@memory-usage" ygotAnnotation:"true"`
	MemoryUtilization  *uint8            `path:"state/memory-utilization" module:"openconfig-system"`
	ΛMemoryUtilization []ygot.Annotation `path:"state/@memory-utilization" ygotAnnotation:"true"`
	Name               *string           `path:"state/name" module:"openconfig-system"`
	ΛName              []ygot.Annotation `path:"state/@name" ygotAnnotation:"true"`
	Pid                *uint64           `path:"state/pid|pid" module:"openconfig-system"`
	ΛPid               []ygot.Annotation `path:"state/@pid|@pid" ygotAnnotation:"true"`
	StartTime          *uint64           `path:"state/start-time" module:"openconfig-system"`
	ΛStartTime         []ygot.Annotation `path:"state/@start-time" ygotAnnotation:"true"`
	Uptime             *uint64           `path:"state/uptime" module:"openconfig-system"`
	ΛUptime            []ygot.Annotation `path:"state/@uptime" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_Process implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_Process) IsYANGGoStruct() {}

// System_SshServer represents the /openconfig-system/system/ssh-server YANG schema element.
type System_SshServer struct {
	ΛMetadata        []ygot.Annotation                                    `path:"@" ygotAnnotation:"true"`
	Enable           *bool                                                `path:"config/enable" module:"openconfig-system"`
	ΛEnable          []ygot.Annotation                                    `path:"config/@enable" ygotAnnotation:"true"`
	ProtocolVersion  E_OpenconfigSystemTerminal_SshServer_ProtocolVersion `path:"config/protocol-version" module:"openconfig-system"`
	ΛProtocolVersion []ygot.Annotation                                    `path:"config/@protocol-version" ygotAnnotation:"true"`
	RateLimit        *uint16                                              `path:"config/rate-limit" module:"openconfig-system"`
	ΛRateLimit       []ygot.Annotation                                    `path:"config/@rate-limit" ygotAnnotation:"true"`
	SessionLimit     *uint16                                              `path:"config/session-limit" module:"openconfig-system"`
	ΛSessionLimit    []ygot.Annotation                                    `path:"config/@session-limit" ygotAnnotation:"true"`
	Timeout          *uint16                                              `path:"config/timeout" module:"openconfig-system"`
	ΛTimeout         []ygot.Annotation                                    `path:"config/@timeout" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_SshServer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_SshServer) IsYANGGoStruct() {}

// System_TelnetServer represents the /openconfig-system/system/telnet-server YANG schema element.
type System_TelnetServer struct {
	ΛMetadata     []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Enable        *bool             `path:"config/enable" module:"openconfig-system"`
	ΛEnable       []ygot.Annotation `path:"config/@enable" ygotAnnotation:"true"`
	RateLimit     *uint16           `path:"config/rate-limit" module:"openconfig-system"`
	ΛRateLimit    []ygot.Annotation `path:"config/@rate-limit" ygotAnnotation:"true"`
	SessionLimit  *uint16           `path:"config/session-limit" module:"openconfig-system"`
	ΛSessionLimit []ygot.Annotation `path:"config/@session-limit" ygotAnnotation:"true"`
	Timeout       *uint16           `path:"config/timeout" module:"openconfig-system"`
	ΛTimeout      []ygot.Annotation `path:"config/@timeout" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that System_TelnetServer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*System_TelnetServer) IsYANGGoStruct() {}
