/*
Package exampleoc is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

NOTE WELL: This is an example code file that is distributed with ygot.
It should not be used within your application, as it WILL change,
without warning. Rather, you should generate structs directly from
OpenConfig models using the ygot package.

This package was generated by github.com/openconfig/ygot
using the following YANG input files:
	- public/release/models/network-instance/openconfig-network-instance.yang
	- public/release/models/optical-transport/openconfig-optical-amplifier.yang
	- public/release/models/optical-transport/openconfig-terminal-device.yang
	- public/release/models/optical-transport/openconfig-transport-line-protection.yang
	- public/release/models/platform/openconfig-platform.yang
	- public/release/models/policy/openconfig-routing-policy.yang
	- public/release/models/lacp/openconfig-lacp.yang
	- public/release/models/system/openconfig-system.yang
	- public/release/models/lldp/openconfig-lldp.yang
	- public/release/models/stp/openconfig-spanning-tree.yang
	- public/release/models/interfaces/openconfig-interfaces.yang
	- public/release/models/interfaces/openconfig-if-ip.yang
	- public/release/models/interfaces/openconfig-if-aggregate.yang
	- public/release/models/interfaces/openconfig-if-ethernet.yang
	- public/release/models/interfaces/openconfig-if-ip-ext.yang
Imported modules were sourced from:
	- public/...
	- deps/...
*/
package exampleoc

import (
	"github.com/openconfig/ygot/ygot"
)

// TerminalDevice represents the /openconfig-terminal-device/terminal-device YANG schema element.
type TerminalDevice struct {
	ΛMetadata []ygot.Annotation                  `path:"@" ygotAnnotation:"true"`
	Channel   map[uint32]*TerminalDevice_Channel `path:"logical-channels/channel" module:"openconfig-terminal-device"`
	ΛChannel  []ygot.Annotation                  `path:"logical-channels/@channel" ygotAnnotation:"true"`
	Mode      map[uint16]*TerminalDevice_Mode    `path:"operational-modes/mode" module:"openconfig-terminal-device"`
	ΛMode     []ygot.Annotation                  `path:"operational-modes/@mode" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice) IsYANGGoStruct() {}

// TerminalDevice_Channel represents the /openconfig-terminal-device/terminal-device/logical-channels/channel YANG schema element.
type TerminalDevice_Channel struct {
	ΛMetadata           []ygot.Annotation                                        `path:"@" ygotAnnotation:"true"`
	AdminState          E_OpenconfigTerminalDevice_AdminStateType                `path:"config/admin-state" module:"openconfig-terminal-device"`
	ΛAdminState         []ygot.Annotation                                        `path:"config/@admin-state" ygotAnnotation:"true"`
	Assignment          map[uint32]*TerminalDevice_Channel_Assignment            `path:"logical-channel-assignments/assignment" module:"openconfig-terminal-device"`
	ΛAssignment         []ygot.Annotation                                        `path:"logical-channel-assignments/@assignment" ygotAnnotation:"true"`
	Description         *string                                                  `path:"config/description" module:"openconfig-terminal-device"`
	ΛDescription        []ygot.Annotation                                        `path:"config/@description" ygotAnnotation:"true"`
	Ethernet            *TerminalDevice_Channel_Ethernet                         `path:"ethernet" module:"openconfig-terminal-device"`
	ΛEthernet           []ygot.Annotation                                        `path:"@ethernet" ygotAnnotation:"true"`
	Index               *uint32                                                  `path:"config/index|index" module:"openconfig-terminal-device"`
	ΛIndex              []ygot.Annotation                                        `path:"config/@index|@index" ygotAnnotation:"true"`
	Ingress             *TerminalDevice_Channel_Ingress                          `path:"ingress" module:"openconfig-terminal-device"`
	ΛIngress            []ygot.Annotation                                        `path:"@ingress" ygotAnnotation:"true"`
	LinkState           E_OpenconfigTerminalDevice_Channel_LinkState             `path:"state/link-state" module:"openconfig-terminal-device"`
	ΛLinkState          []ygot.Annotation                                        `path:"state/@link-state" ygotAnnotation:"true"`
	LogicalChannelType  E_OpenconfigTransportTypes_LOGICAL_ELEMENT_PROTOCOL_TYPE `path:"config/logical-channel-type" module:"openconfig-terminal-device"`
	ΛLogicalChannelType []ygot.Annotation                                        `path:"config/@logical-channel-type" ygotAnnotation:"true"`
	LoopbackMode        E_OpenconfigTerminalDevice_LoopbackModeType              `path:"config/loopback-mode" module:"openconfig-terminal-device"`
	ΛLoopbackMode       []ygot.Annotation                                        `path:"config/@loopback-mode" ygotAnnotation:"true"`
	Otn                 *TerminalDevice_Channel_Otn                              `path:"otn" module:"openconfig-terminal-device"`
	ΛOtn                []ygot.Annotation                                        `path:"@otn" ygotAnnotation:"true"`
	RateClass           E_OpenconfigTransportTypes_TRIBUTARY_RATE_CLASS_TYPE     `path:"config/rate-class" module:"openconfig-terminal-device"`
	ΛRateClass          []ygot.Annotation                                        `path:"config/@rate-class" ygotAnnotation:"true"`
	TestSignal          *bool                                                    `path:"config/test-signal" module:"openconfig-terminal-device"`
	ΛTestSignal         []ygot.Annotation                                        `path:"config/@test-signal" ygotAnnotation:"true"`
	TribProtocol        E_OpenconfigTransportTypes_TRIBUTARY_PROTOCOL_TYPE       `path:"config/trib-protocol" module:"openconfig-terminal-device"`
	ΛTribProtocol       []ygot.Annotation                                        `path:"config/@trib-protocol" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel) IsYANGGoStruct() {}

// TerminalDevice_Channel_Assignment represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/logical-channel-assignments/assignment YANG schema element.
type TerminalDevice_Channel_Assignment struct {
	ΛMetadata       []ygot.Annotation                                    `path:"@" ygotAnnotation:"true"`
	Allocation      *float64                                             `path:"config/allocation" module:"openconfig-terminal-device"`
	ΛAllocation     []ygot.Annotation                                    `path:"config/@allocation" ygotAnnotation:"true"`
	AssignmentType  E_OpenconfigTerminalDevice_Assignment_AssignmentType `path:"config/assignment-type" module:"openconfig-terminal-device"`
	ΛAssignmentType []ygot.Annotation                                    `path:"config/@assignment-type" ygotAnnotation:"true"`
	Description     *string                                              `path:"config/description" module:"openconfig-terminal-device"`
	ΛDescription    []ygot.Annotation                                    `path:"config/@description" ygotAnnotation:"true"`
	Index           *uint32                                              `path:"config/index|index" module:"openconfig-terminal-device"`
	ΛIndex          []ygot.Annotation                                    `path:"config/@index|@index" ygotAnnotation:"true"`
	LogicalChannel  *uint32                                              `path:"config/logical-channel" module:"openconfig-terminal-device"`
	ΛLogicalChannel []ygot.Annotation                                    `path:"config/@logical-channel" ygotAnnotation:"true"`
	OpticalChannel  *string                                              `path:"config/optical-channel" module:"openconfig-terminal-device"`
	ΛOpticalChannel []ygot.Annotation                                    `path:"config/@optical-channel" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Assignment implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Assignment) IsYANGGoStruct() {}

// TerminalDevice_Channel_Ethernet represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/ethernet YANG schema element.
type TerminalDevice_Channel_Ethernet struct {
	ΛMetadata            []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	In_8021QFrames       *uint64           `path:"state/in-8021q-frames" module:"openconfig-terminal-device"`
	ΛIn_8021QFrames      []ygot.Annotation `path:"state/@in-8021q-frames" ygotAnnotation:"true"`
	InCrcErrors          *uint64           `path:"state/in-crc-errors" module:"openconfig-terminal-device"`
	ΛInCrcErrors         []ygot.Annotation `path:"state/@in-crc-errors" ygotAnnotation:"true"`
	InFragmentFrames     *uint64           `path:"state/in-fragment-frames" module:"openconfig-terminal-device"`
	ΛInFragmentFrames    []ygot.Annotation `path:"state/@in-fragment-frames" ygotAnnotation:"true"`
	InJabberFrames       *uint64           `path:"state/in-jabber-frames" module:"openconfig-terminal-device"`
	ΛInJabberFrames      []ygot.Annotation `path:"state/@in-jabber-frames" ygotAnnotation:"true"`
	InMacControlFrames   *uint64           `path:"state/in-mac-control-frames" module:"openconfig-terminal-device"`
	ΛInMacControlFrames  []ygot.Annotation `path:"state/@in-mac-control-frames" ygotAnnotation:"true"`
	InMacPauseFrames     *uint64           `path:"state/in-mac-pause-frames" module:"openconfig-terminal-device"`
	ΛInMacPauseFrames    []ygot.Annotation `path:"state/@in-mac-pause-frames" ygotAnnotation:"true"`
	InOversizeFrames     *uint64           `path:"state/in-oversize-frames" module:"openconfig-terminal-device"`
	ΛInOversizeFrames    []ygot.Annotation `path:"state/@in-oversize-frames" ygotAnnotation:"true"`
	Out_8021QFrames      *uint64           `path:"state/out-8021q-frames" module:"openconfig-terminal-device"`
	ΛOut_8021QFrames     []ygot.Annotation `path:"state/@out-8021q-frames" ygotAnnotation:"true"`
	OutMacControlFrames  *uint64           `path:"state/out-mac-control-frames" module:"openconfig-terminal-device"`
	ΛOutMacControlFrames []ygot.Annotation `path:"state/@out-mac-control-frames" ygotAnnotation:"true"`
	OutMacPauseFrames    *uint64           `path:"state/out-mac-pause-frames" module:"openconfig-terminal-device"`
	ΛOutMacPauseFrames   []ygot.Annotation `path:"state/@out-mac-pause-frames" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Ethernet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Ethernet) IsYANGGoStruct() {}

// TerminalDevice_Channel_Ingress represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/ingress YANG schema element.
type TerminalDevice_Channel_Ingress struct {
	ΛMetadata        []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	PhysicalChannel  []uint16          `path:"config/physical-channel" module:"openconfig-terminal-device"`
	ΛPhysicalChannel []ygot.Annotation `path:"config/@physical-channel" ygotAnnotation:"true"`
	Transceiver      *string           `path:"config/transceiver" module:"openconfig-terminal-device"`
	ΛTransceiver     []ygot.Annotation `path:"config/@transceiver" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Ingress implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Ingress) IsYANGGoStruct() {}

// TerminalDevice_Channel_Otn represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/otn YANG schema element.
type TerminalDevice_Channel_Otn struct {
	ΛMetadata               []ygot.Annotation                      `path:"@" ygotAnnotation:"true"`
	BackgroundBlockErrors   *uint64                                `path:"state/background-block-errors" module:"openconfig-terminal-device"`
	ΛBackgroundBlockErrors  []ygot.Annotation                      `path:"state/@background-block-errors" ygotAnnotation:"true"`
	CodeViolations          *uint64                                `path:"state/code-violations" module:"openconfig-terminal-device"`
	ΛCodeViolations         []ygot.Annotation                      `path:"state/@code-violations" ygotAnnotation:"true"`
	ErroredSeconds          *uint64                                `path:"state/errored-seconds" module:"openconfig-terminal-device"`
	ΛErroredSeconds         []ygot.Annotation                      `path:"state/@errored-seconds" ygotAnnotation:"true"`
	Esnr                    *TerminalDevice_Channel_Otn_Esnr       `path:"state/esnr" module:"openconfig-terminal-device"`
	ΛEsnr                   []ygot.Annotation                      `path:"state/@esnr" ygotAnnotation:"true"`
	FecCorrectedBits        *uint64                                `path:"state/fec-corrected-bits" module:"openconfig-terminal-device"`
	ΛFecCorrectedBits       []ygot.Annotation                      `path:"state/@fec-corrected-bits" ygotAnnotation:"true"`
	FecCorrectedBytes       *uint64                                `path:"state/fec-corrected-bytes" module:"openconfig-terminal-device"`
	ΛFecCorrectedBytes      []ygot.Annotation                      `path:"state/@fec-corrected-bytes" ygotAnnotation:"true"`
	FecUncorrectableWords   *uint64                                `path:"state/fec-uncorrectable-words" module:"openconfig-terminal-device"`
	ΛFecUncorrectableWords  []ygot.Annotation                      `path:"state/@fec-uncorrectable-words" ygotAnnotation:"true"`
	PostFecBer              *TerminalDevice_Channel_Otn_PostFecBer `path:"state/post-fec-ber" module:"openconfig-terminal-device"`
	ΛPostFecBer             []ygot.Annotation                      `path:"state/@post-fec-ber" ygotAnnotation:"true"`
	PreFecBer               *TerminalDevice_Channel_Otn_PreFecBer  `path:"state/pre-fec-ber" module:"openconfig-terminal-device"`
	ΛPreFecBer              []ygot.Annotation                      `path:"state/@pre-fec-ber" ygotAnnotation:"true"`
	QValue                  *TerminalDevice_Channel_Otn_QValue     `path:"state/q-value" module:"openconfig-terminal-device"`
	ΛQValue                 []ygot.Annotation                      `path:"state/@q-value" ygotAnnotation:"true"`
	RdiMsg                  *string                                `path:"state/rdi-msg" module:"openconfig-terminal-device"`
	ΛRdiMsg                 []ygot.Annotation                      `path:"state/@rdi-msg" ygotAnnotation:"true"`
	SeverelyErroredSeconds  *uint64                                `path:"state/severely-errored-seconds" module:"openconfig-terminal-device"`
	ΛSeverelyErroredSeconds []ygot.Annotation                      `path:"state/@severely-errored-seconds" ygotAnnotation:"true"`
	TtiMsgAuto              *bool                                  `path:"config/tti-msg-auto" module:"openconfig-terminal-device"`
	ΛTtiMsgAuto             []ygot.Annotation                      `path:"config/@tti-msg-auto" ygotAnnotation:"true"`
	TtiMsgExpected          *string                                `path:"config/tti-msg-expected" module:"openconfig-terminal-device"`
	ΛTtiMsgExpected         []ygot.Annotation                      `path:"config/@tti-msg-expected" ygotAnnotation:"true"`
	TtiMsgRecv              *string                                `path:"state/tti-msg-recv" module:"openconfig-terminal-device"`
	ΛTtiMsgRecv             []ygot.Annotation                      `path:"state/@tti-msg-recv" ygotAnnotation:"true"`
	TtiMsgTransmit          *string                                `path:"config/tti-msg-transmit" module:"openconfig-terminal-device"`
	ΛTtiMsgTransmit         []ygot.Annotation                      `path:"config/@tti-msg-transmit" ygotAnnotation:"true"`
	UnavailableSeconds      *uint64                                `path:"state/unavailable-seconds" module:"openconfig-terminal-device"`
	ΛUnavailableSeconds     []ygot.Annotation                      `path:"state/@unavailable-seconds" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Otn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Otn) IsYANGGoStruct() {}

// TerminalDevice_Channel_Otn_Esnr represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/otn/state/esnr YANG schema element.
type TerminalDevice_Channel_Otn_Esnr struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-terminal-device"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-terminal-device"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-terminal-device"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-terminal-device"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-terminal-device"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Otn_Esnr implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Otn_Esnr) IsYANGGoStruct() {}

// TerminalDevice_Channel_Otn_PostFecBer represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/otn/state/post-fec-ber YANG schema element.
type TerminalDevice_Channel_Otn_PostFecBer struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-terminal-device"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-terminal-device"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-terminal-device"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-terminal-device"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Otn_PostFecBer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Otn_PostFecBer) IsYANGGoStruct() {}

// TerminalDevice_Channel_Otn_PreFecBer represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/otn/state/pre-fec-ber YANG schema element.
type TerminalDevice_Channel_Otn_PreFecBer struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-terminal-device"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-terminal-device"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-terminal-device"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-terminal-device"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Otn_PreFecBer implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Otn_PreFecBer) IsYANGGoStruct() {}

// TerminalDevice_Channel_Otn_QValue represents the /openconfig-terminal-device/terminal-device/logical-channels/channel/otn/state/q-value YANG schema element.
type TerminalDevice_Channel_Otn_QValue struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-terminal-device"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-terminal-device"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-terminal-device"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-terminal-device"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-terminal-device"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Channel_Otn_QValue implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Channel_Otn_QValue) IsYANGGoStruct() {}

// TerminalDevice_Mode represents the /openconfig-terminal-device/terminal-device/operational-modes/mode YANG schema element.
type TerminalDevice_Mode struct {
	ΛMetadata    []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Description  *string           `path:"state/description" module:"openconfig-terminal-device"`
	ΛDescription []ygot.Annotation `path:"state/@description" ygotAnnotation:"true"`
	ModeId       *uint16           `path:"state/mode-id|mode-id" module:"openconfig-terminal-device"`
	ΛModeId      []ygot.Annotation `path:"state/@mode-id|@mode-id" ygotAnnotation:"true"`
	VendorId     *string           `path:"state/vendor-id" module:"openconfig-terminal-device"`
	ΛVendorId    []ygot.Annotation `path:"state/@vendor-id" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that TerminalDevice_Mode implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*TerminalDevice_Mode) IsYANGGoStruct() {}
