/*
Package exampleoc is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

NOTE WELL: This is an example code file that is distributed with ygot.
It should not be used within your application, as it WILL change,
without warning. Rather, you should generate structs directly from
OpenConfig models using the ygot package.

This package was generated by github.com/openconfig/ygot
using the following YANG input files:
	- public/release/models/network-instance/openconfig-network-instance.yang
	- public/release/models/optical-transport/openconfig-optical-amplifier.yang
	- public/release/models/optical-transport/openconfig-terminal-device.yang
	- public/release/models/optical-transport/openconfig-transport-line-protection.yang
	- public/release/models/platform/openconfig-platform.yang
	- public/release/models/policy/openconfig-routing-policy.yang
	- public/release/models/lacp/openconfig-lacp.yang
	- public/release/models/system/openconfig-system.yang
	- public/release/models/lldp/openconfig-lldp.yang
	- public/release/models/stp/openconfig-spanning-tree.yang
	- public/release/models/interfaces/openconfig-interfaces.yang
	- public/release/models/interfaces/openconfig-if-ip.yang
	- public/release/models/interfaces/openconfig-if-aggregate.yang
	- public/release/models/interfaces/openconfig-if-ethernet.yang
	- public/release/models/interfaces/openconfig-if-ip-ext.yang
Imported modules were sourced from:
	- public/...
	- deps/...
*/
package exampleoc

import (
	"github.com/openconfig/ygot/ygot"
)

// Aps represents the /openconfig-transport-line-protection/aps YANG schema element.
type Aps struct {
	ΛMetadata  []ygot.Annotation         `path:"@" ygotAnnotation:"true"`
	ApsModule  map[string]*Aps_ApsModule `path:"aps-modules/aps-module" module:"openconfig-transport-line-protection"`
	ΛApsModule []ygot.Annotation         `path:"aps-modules/@aps-module" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps) IsYANGGoStruct() {}

// Aps_ApsModule represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module YANG schema element.
type Aps_ApsModule struct {
	ΛMetadata                  []ygot.Annotation                             `path:"@" ygotAnnotation:"true"`
	ActivePath                 E_OpenconfigTransportLineProtection_APS_PATHS `path:"state/active-path" module:"openconfig-transport-line-protection"`
	ΛActivePath                []ygot.Annotation                             `path:"state/@active-path" ygotAnnotation:"true"`
	Name                       *string                                       `path:"config/name|name" module:"openconfig-transport-line-protection"`
	ΛName                      []ygot.Annotation                             `path:"config/@name|@name" ygotAnnotation:"true"`
	Ports                      *Aps_ApsModule_Ports                          `path:"ports" module:"openconfig-transport-line-protection"`
	ΛPorts                     []ygot.Annotation                             `path:"@ports" ygotAnnotation:"true"`
	PrimarySwitchHysteresis    *float64                                      `path:"config/primary-switch-hysteresis" module:"openconfig-transport-line-protection"`
	ΛPrimarySwitchHysteresis   []ygot.Annotation                             `path:"config/@primary-switch-hysteresis" ygotAnnotation:"true"`
	PrimarySwitchThreshold     *float64                                      `path:"config/primary-switch-threshold" module:"openconfig-transport-line-protection"`
	ΛPrimarySwitchThreshold    []ygot.Annotation                             `path:"config/@primary-switch-threshold" ygotAnnotation:"true"`
	Revertive                  *bool                                         `path:"config/revertive" module:"openconfig-transport-line-protection"`
	ΛRevertive                 []ygot.Annotation                             `path:"config/@revertive" ygotAnnotation:"true"`
	SecondarySwitchHysteresis  *float64                                      `path:"config/secondary-switch-hysteresis" module:"openconfig-transport-line-protection"`
	ΛSecondarySwitchHysteresis []ygot.Annotation                             `path:"config/@secondary-switch-hysteresis" ygotAnnotation:"true"`
	SecondarySwitchThreshold   *float64                                      `path:"config/secondary-switch-threshold" module:"openconfig-transport-line-protection"`
	ΛSecondarySwitchThreshold  []ygot.Annotation                             `path:"config/@secondary-switch-threshold" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule) IsYANGGoStruct() {}

// Aps_ApsModule_Ports represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports YANG schema element.
type Aps_ApsModule_Ports struct {
	ΛMetadata         []ygot.Annotation                     `path:"@" ygotAnnotation:"true"`
	CommonIn          *Aps_ApsModule_Ports_CommonIn         `path:"common-in" module:"openconfig-transport-line-protection"`
	ΛCommonIn         []ygot.Annotation                     `path:"@common-in" ygotAnnotation:"true"`
	CommonOutput      *Aps_ApsModule_Ports_CommonOutput     `path:"common-output" module:"openconfig-transport-line-protection"`
	ΛCommonOutput     []ygot.Annotation                     `path:"@common-output" ygotAnnotation:"true"`
	LinePrimaryIn     *Aps_ApsModule_Ports_LinePrimaryIn    `path:"line-primary-in" module:"openconfig-transport-line-protection"`
	ΛLinePrimaryIn    []ygot.Annotation                     `path:"@line-primary-in" ygotAnnotation:"true"`
	LinePrimaryOut    *Aps_ApsModule_Ports_LinePrimaryOut   `path:"line-primary-out" module:"openconfig-transport-line-protection"`
	ΛLinePrimaryOut   []ygot.Annotation                     `path:"@line-primary-out" ygotAnnotation:"true"`
	LineSecondaryIn   *Aps_ApsModule_Ports_LineSecondaryIn  `path:"line-secondary-in" module:"openconfig-transport-line-protection"`
	ΛLineSecondaryIn  []ygot.Annotation                     `path:"@line-secondary-in" ygotAnnotation:"true"`
	LineSecondaryOut  *Aps_ApsModule_Ports_LineSecondaryOut `path:"line-secondary-out" module:"openconfig-transport-line-protection"`
	ΛLineSecondaryOut []ygot.Annotation                     `path:"@line-secondary-out" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-in YANG schema element.
type Aps_ApsModule_Ports_CommonIn struct {
	ΛMetadata          []ygot.Annotation                          `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                   `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                          `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                      `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                          `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_CommonIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                          `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                   `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                          `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_CommonIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonOutput represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-output YANG schema element.
type Aps_ApsModule_Ports_CommonOutput struct {
	ΛMetadata          []ygot.Annotation                              `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                       `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                              `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_CommonOutput_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                              `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                       `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                              `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonOutput implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonOutput) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_CommonOutput_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/common-output/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_CommonOutput_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_CommonOutput_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_CommonOutput_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-in YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryIn struct {
	ΛMetadata          []ygot.Annotation                               `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                        `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                               `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                           `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                               `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                               `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                        `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                               `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryOut represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-out YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryOut struct {
	ΛMetadata          []ygot.Annotation                                `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                         `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                         `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryOut implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryOut) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-primary-out/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LinePrimaryOut_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryIn represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-in YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryIn struct {
	ΛMetadata          []ygot.Annotation                                 `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                          `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                 `path:"state/@attenuation" ygotAnnotation:"true"`
	Enabled            *bool                                             `path:"config/enabled" module:"openconfig-transport-line-protection"`
	ΛEnabled           []ygot.Annotation                                 `path:"config/@enabled" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                 `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                          `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                 `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryIn implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryIn) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-in/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryIn_OpticalPower) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryOut represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-out YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryOut struct {
	ΛMetadata          []ygot.Annotation                                  `path:"@" ygotAnnotation:"true"`
	Attenuation        *float64                                           `path:"state/attenuation" module:"openconfig-transport-line-protection"`
	ΛAttenuation       []ygot.Annotation                                  `path:"state/@attenuation" ygotAnnotation:"true"`
	OpticalPower       *Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower `path:"state/optical-power" module:"openconfig-transport-line-protection"`
	ΛOpticalPower      []ygot.Annotation                                  `path:"state/@optical-power" ygotAnnotation:"true"`
	TargetAttenuation  *float64                                           `path:"config/target-attenuation" module:"openconfig-transport-line-protection"`
	ΛTargetAttenuation []ygot.Annotation                                  `path:"config/@target-attenuation" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryOut implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryOut) IsYANGGoStruct() {}

// Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower represents the /openconfig-transport-line-protection/aps/aps-modules/aps-module/ports/line-secondary-out/state/optical-power YANG schema element.
type Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower struct {
	ΛMetadata []ygot.Annotation `path:"@" ygotAnnotation:"true"`
	Avg       *float64          `path:"avg" module:"openconfig-transport-line-protection"`
	ΛAvg      []ygot.Annotation `path:"@avg" ygotAnnotation:"true"`
	Instant   *float64          `path:"instant" module:"openconfig-transport-line-protection"`
	ΛInstant  []ygot.Annotation `path:"@instant" ygotAnnotation:"true"`
	Interval  *uint64           `path:"interval" module:"openconfig-transport-line-protection"`
	ΛInterval []ygot.Annotation `path:"@interval" ygotAnnotation:"true"`
	Max       *float64          `path:"max" module:"openconfig-transport-line-protection"`
	ΛMax      []ygot.Annotation `path:"@max" ygotAnnotation:"true"`
	Min       *float64          `path:"min" module:"openconfig-transport-line-protection"`
	ΛMin      []ygot.Annotation `path:"@min" ygotAnnotation:"true"`
}

// IsYANGGoStruct ensures that Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Aps_ApsModule_Ports_LineSecondaryOut_OpticalPower) IsYANGGoStruct() {}
